### PR TITLE
siproxd: add link to Wiki page

### PR DESCRIPTION
**Pull request by micmac1**
Add some examples for the regex plugin to UCI configuration. Examples
provided by @biuklija in issue #384.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

-------------------------------

Maintainer: @jslachta 
Compile tested: No (just added comments to config file)
Run tested: No

Description:
Fixes issue #384 

Kind regards,
Seb

### CODE REVIEW

**Comment by guidosarducci** [comment]
Hi Seb,

Although I first added a bunch of these commented-out usage examples to the UCI config, I've started to have "committers remorse" as I realize the file becomes more and more opaque.

I'm thinking now it might be better to pull basic usage information and examples into a co-located "README.md" file, and keep the UCI config as a minimal working config.

This seems more commonly done on the other OpenWrt repos, where it's also been pointed out that any config file comments would be discarded during UCI file processing/rewriting.

What are your thoughts?

Best regards,
Tony

**Comment by guidosarducci** [comment]
Hi Seb,

Thanks for the reminder about (b)! I had forgotten about the absence of any wiki articles, despite being annoyed about it long ago. That seems like a more widely useful option in the long term.

Given an "open" timeline for doing wiki updates though, I've no problem if you want to still merge the examples and give them a temporary home in the meantime.

Thanks again,
Tony

**Comment by guidosarducci** [comment]
Hi Ivan,

Thanks for the offer to contribute; that would be very helpful since not everyone has experience among all the plugins. I've can add a wiki to my (slightly long) list of OpenWrt TODOs, but please don't time me since this would be my first wiki article!

The official docs are a bit lacking, so I expect Thomas Ries is fairly swamped, but he has been very responsive when I've tried to upstream patches in the past.

Like you, I also had to look through source code sometimes while I was updating this package, but the best up-to-date resource I found was the "hidden" examples file in the source tarballs:
`siproxd-0.8.3dev-24Mar2018/doc/siproxd.conf.example`

All the best,
Tony

**Comment by micmac1** [comment]
Hello Tony and Ivan,

The good thing is that the wiki article doesn't need to be complete from the start. It can grow naturally over time.

I think for a start a short description copied from upstream will do. Maybe plaster the regex plugin comments afterwards.

Can we agree on the document location voip/sipproxd? Then I'll just start with the above.

Kind regards,
Seb

**Comment by guidosarducci** [comment]
Yes, please. And thanks!

**Comment by micmac1** [comment]
OK, so I added a Wiki page [here](https://openwrt.org/docs/guide-user/services/voip/siproxd) and changed the commit of this pull request to just link there.

I think this is OK like this. As said, the wiki page can be extended any time.

Kind regards,
Seb

**Comment by guidosarducci** [comment]
Hi Seb,

Pardon the delay. And thanks, I saw the wiki page and that makes a great start for us to build upon!

I also think it would be preferable to add the wiki link to the Makefile package description, as done in many other packages: e.g.
```
define Package/siproxd/description
 Siproxd is a proxy/masquerading daemon for the SIP protocol. Refer to https://openwrt.org/docs/guide-user/services/voip/siproxd for configuration details and examples.
endef
```
This has the advantage of being available in the package catalog, and hence anytime both pre- and post-installation for someone looking for information, using only `opkg info siproxd`. And given the above, I recommend also removing any overloading of `postinstall` for user messaging. That doesn't seem an appropriate usage for the scriptlet and more complexity than we need.

Warm regards,
Tony

**Comment by micmac1** [comment]
Hi Tony,

Good idea. I'll close this pull request and the maybe you can add one for that when you get around to it. ;-)

Kind regards
Seb

**Pull request closed without merging**
