### PR TITLE
CI: add GitHub testing of Pull Requests

### PR DESCRIPTION
**Pull request by aparcar**
Perform formal checks and see if packages compile on multiple
architectures.

Signed-off-by: Paul Spooren <mail@aparcar.org>

### CODE REVIEW

**Comment by micmac1** [comment]
Thanks @aparcar 

Do you want to include "CI: checkout HEAD commit rather than merge commit" in here as well?

Kind regards,
Seb

**Comment by aparcar** [comment]
I'll update this in a bit

**Comment by champtar** [comment]
@aparcar as soon as you are done you can also nuke Circle CI from the org :)

**Comment by micmac1** [comment]
> @aparcar as soon as you are done you can also nuke Circle CI from the org :)

Can we remove circleci from this repo? By just removing the .circleci folder?

**Comment by aparcar** [comment]
I already disabled the we hook but you can additionally remove it.

**Pull request merged**
