### PR TITLE
freeswitch: add patch moving package to PCRE2

### PR DESCRIPTION
**Pull request by Ansuel**
Add paending patch moving package to PCRE2 as PCRE is EOL and won't receive any updates anymore.

These patch were run uder the freeswitch CI and were validated with their unit tests.

Maintainer: Sebastian Kemper <sebastian_ml@gmx.net>

---

@BKPepe probably will take a bit for this to be actually merged upstream but just for reference also here...

### CODE REVIEW

**Comment by Ansuel** [comment]
Also I think I'm reaching a whole new level on persuading this project of remove PCRE from OpenWRT LOL

**Comment by micmac1** [comment]
This is definitely another level. Thanks Christian.

**Comment by BKPepe** [comment]
Okay guys, I see that @Ansuel created PR in upstream - https://github.com/signalwire/freeswitch/pull/2299

Since we are not getting any attention from devs there. Could we merge this, please and as well backport it to the stable branches as well? We need to move on with PCRE removal. :pray:

**Comment by micmac1** [comment]
Am 27. April 2024 10:10:23 UTC schrieb Josef Schlehofer ***@***.***>:
>Okay guys, I see that @Ansuel created PR in upstream - https://github.com/signalwire/freeswitch/pull/2299
>
>Since we are not getting any attention from devs there. Could we merge this, please and as well backport it to the stable branches as well? We need to move on with PCRE removal. :pray:
>

Too invasive for me personally. Needs to go upstream first. Too risky otherwise in my opinion.

**Comment by BKPepe** [comment]
Upstream devs are occupied, @Ansuel did so amazing work while submitting PRs to upstream for other packages, which was migrated to PCRE2, but this one is the last package. 

It is a pity that we can not say that PCRE2 migration is done until someone merge this thing. :-(

Maybe someone can reach them to look into it with higher priority.

**Comment by robimarko** [comment]
I am tempted to merge this since upstream isn't budging and I dont see a point in having this package that depends on library that was removed so its not usable.

**Comment by Ansuel** [comment]
We need some tester tho

Il Lun 26 Ago 2024, 20:27 Robert Marko ***@***.***> ha
scritto:

**Comment by BKPepe** [comment]
Guys, I am thinking maybe a little bit loud and sorry for that, but if upstream does not care, why we should? There was a plenty of time to look at it or at least they could say that they are busy and they will look at it, but that does not happen.

Currently as said, freeswitch is not compiled. What about removing it from the repository? If users would like to have it back, they could argue and convince upstream to look at it.

**Comment by robimarko** [comment]
`libpcre` was dropped after everything else got migrated over to `libcpre2` since `libpcre` is EOL and not maintained anymore.
It was a lengthy process and it definitively was not dropped overnight.

@BKPepe I am not a fan of dropping packages, but it's been like 9 months since this was posted and nobody even bothered to test it and report back.
I thought that removing `libpcre` would make its users surface but it doesn't seem so.

**Comment by BKPepe** [comment]
Yeah, I agree with what @robimarko said. Basically, the same is what I wanted to say. 💯  We need to be a little bit more progressive. Otherwise, we would have ``libpcre`` in our repository for ages. However, 9 months it is quite a long time to look at it.

> I thought that removing `libpcre` would make its users surface but it doesn't seem so.

It is also possible that many users are waiting until it is missing in the stable release.

**Comment by BKPepe** [comment]
As there seems to be radio silence, I think we really need to drop this package.

**Comment by micmac1** [comment]
Am Mon, Sep 23, 2024 at 01:36:51AM -0700 schrieb Josef Schlehofer:
> As there seems to be radio silence, I think we really need to drop this package.

Don't agree. It's already marked as BROKEN. No removal necessary.

**Comment by BKPepe** [comment]
It is not marked as broken, because buildbots are still trying to compile this package. It can be seen here:
https://downloads.openwrt.org/snapshots/faillogs/arm_cortex-a9_vfpv3-d16/telephony/freeswitch/compile.txt

Its failing, because of missing libpcre.

**Comment by micmac1** [comment]
It is marked BROKEN in Makefile. In SDK it doesn't show up in menuconfig as expected. If buildbots still try to build it maybe it's a separate issue.

**Comment by Ansuel** [comment]
Instead of keeping broken and all this war... Is it possible to find a community of user that makes use of the regex feature of this package and just push to have this feature in?

I feel we are just wasting time with this talk instead of putting effort in testing the proposed code...

It's sad honestly putting all these effort in migrating big project to a whole new library and then receive random "NO" without reason. It's like hearing "nobody asked that you just wasted your time"

**Comment by jslachta** [comment]
For these cases, I would welcome an analogy to the Debian-Experimental repository with applied workarounds to make this functional. It wouldn't break the consistency of the package builds, and at the same time, we wouldn’t have to push FreeSwitch users toward another distribution. I would prefer to keep such a large package with a long history and a fairly wide user base. Not everyone has the time or resources to prepare the entire distribution or the packages themselves.

**Comment by Ansuel** [comment]
> fairly wide user base

so wide in almost a year not a single user came to test the changes :(

**Comment by jslachta** [comment]
> > fairly wide user base
> 
> so wide in almost a year not a single user came to test the changes :(

Most of the FreeSwitch users I know do not build OpenWrt themselves; they simply use what they get. Some of them stick with older OpenWrt versions, while others have migrated to Asterisk.

**Comment by Ansuel** [comment]
> Most of the FreeSwitch users I know do not build OpenWrt themselves

that is really not a problem. Given the situation we can totally build the package or the binary and ask them to test

**Comment by BKPepe** [comment]
Because branch-off is coming. What we should do with this PR?
- Merge this
Con: Testing on users. 🤔 
- Close this and remove this package

There would be third option, but upstream developers are not interested in this.

**Comment by stintel** [comment]
> > fairly wide user base
> 
> so wide in almost a year not a single user came to test the changes :(

Too bad I didn't notice this earlier. Found this PR utterly annoyed by freeswitch having disappeared from my image without any warning whatsoever. PR updated, build -and runtime tested on x86/64. Was able to make a phone call to my mobile phone, with a C7941 running SIP firmware, connected to FreeSWITCH running on OpenWrt, using a 3rd-party SIP gateway. Not sure why CI is shitting itself at least for powerpc_464fp, but since this appears to happen all the time, please just merge and get this over with.

**Pull request merged**
