### PR TITLE
Many Changes...

### PR DESCRIPTION
**Pull request by redfox1977**
I've change the Asterisk-Version, add the Soundpacket and add the Confbridge with the bridge_simple.so module to make the sip function..

### CODE REVIEW

**Comment by redfox1977** [comment]
It is my frist Pullrequest, i hope i make no mistakes..

**Comment by jslachta** [comment]
Several notes to your PR:

* please follow the [Contributing guidelines](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md "Contributing guidelines"):
* please make atomic changes - package updates should be made separately from package fixes and module additions
* your module addition - res-srtp - provides res_rtp_multicast.so? Did you want to provide res_srtp.so?

As for the contributing guidelines:
* your commit title lacks short description of changes made to the package
* your commit title lacks package prefix
* your commit lacks signed-off-by line

**Comment by redfox1977** [comment]
Sorry, wanted to improve only help Asterisk.
Had the makefile tested by me and it runs very well.
Should I submit the changes again?

**Comment by jslachta** [comment]
If you could it, please submit it again..

**Comment by redfox1977** [comment]
I've mad it again, is this correct?


Von Samsung Mobile gesendet

-------- Ursprüngliche Nachricht --------
Von: Jiri Slachta <notifications@github.com> 
Datum: 21.04.2015  16:24  (GMT+01:00) 
An: openwrt/telephony <telephony@noreply.github.com> 
Cc: Sven Pietack <redfox7719@googlemail.com> 
Betreff: Re: [telephony] Many Changes... (#36) 
 
If you could it, please submit it again..

**Pull request closed without merging**
