### PR TITLE
sipgrep: Move package to PCRE2

### PR DESCRIPTION
**Pull request by Ansuel**
Add patch to convert the package to PCRE2 as PCRE is EOL and won't receive any security updates anymore.

Maintainer: Sebastian Kemper <sebastian_ml@gmx.net>

### CODE REVIEW

**Comment by Ansuel** [comment]
@BKPepe easy to convert... hope upstream will merge this but i doubt since it's a pretty old project

**Comment by Ansuel** [comment]
They actually merged the patch upstream... So this is actually now a backport!

**Comment by BKPepe** [comment]
Reference: https://github.com/sipcapture/sipgrep/pull/43

**Review by BKPepe — APPROVED** [review]
Thank you, @Ansuel. Great work as always! 👏

**Comment by micmac1** [comment]
Thanks Christian!

**Comment by BKPepe** [comment]
Would it be possible to backport this change to OpenWrt 23.05 branch, please? :)

**Pull request merged**
