### PR TITLE
dahdi-linux: bump to latest git head

### PR DESCRIPTION
**Pull request by micmac1**
This compiles with newer kernels now.

Maintainer: N/A
Compile tested: sdk-ipq807x (kernel 6) sdk-ath79 (kernel 5)
Run tested: N/A

Description:
Hi @ john-tho 

I tried upstream master and it compiles now. Are you OK with this?

Kind regards,
Seb

### CODE REVIEW

**Comment by Ansuel** [comment]
mhhh can't we bump to a stable release and backport the needed patches? the error with std is a missing configure option so it should be just a patch to backport (if it's not already included in 3.2.0)

**Comment by micmac1** [comment]
It's quite a lot of patches, even if you update to 3.2.0, see PR #786. If john-tho updates his pull request I'd be fine with this approach, though, obviously.

In my opinion this is a legacy package with limited upstream support, so keeping our efforts as minimal as possible seems like a measured approach.

**Comment by voltagex** [comment]
I hit this compile error without explicitly asking for it to be built - how can I disable it so that my build can succeed for the moment?

**Comment by micmac1** [comment]
Try disabling the VoIP kernel modules. Or maybe uninstall the package temporarily (./scripts/feeds uninstall dahdi-linux) and rerun menuconfig.

**Pull request merged**
