### PR TITLE
asterisk: update to version 20.8.1

### PR DESCRIPTION
**Pull request by dangowrt**
Maintainer: @jslachta 
Compile tested: x86/64
Run tested: x86/64 (chan-sip, chan-iax, many applications), lantiq/xrx200 (chan-lantiq and pjsip only)

Description:
Update to most recent LTS release addressing multiple security and stability issues.

Complete changelog:
https://github.com/asterisk/asterisk/compare/20.5.2...20.8.1

Note that res-stir-shaken switched to use libjwt instead of providing a built-in JWT implementation.

Addition of libjwt is pending in packages repo, see https://github.com/openwrt/packages/pull/24446

### CODE REVIEW

**Comment by jslachta** [comment]
Hi Daniel (@dangowrt), 

thank you for your PR. I am currently out of capacity for run testing it.. does it work? Otherwise it looks good to me.

Kind regards,
Jiri

**Review by jslachta — APPROVED** [review]

**Comment by dangowrt** [comment]
I'm currently testing it excessively on x86/64 as part of this year's [Cosmic Cable Ltd.](https://cosmic.cable.limited/about.html) installation on [Fusion Festival](https://www.fusion-festival.de/en/).

I will test chan-lantiq on arcadyan,vgv7510kw22-nor (o2 Box 6431) later today.

**Comment by dhewg** [comment]
I'm running this on ipq40xx for a few weeks now, and my setup works just fine with it!
I did bump pjproject though, to the same version that's bundled with asterisk 20.8.1:
https://github.com/dhewg/telephony/commit/9d46b7aeeaac5838c0b71f87160da40f1a7b580b

**Comment by dangowrt** [comment]
Tested asterisk-chan-lantiq as well now, works fine.

**Comment by jslachta** [comment]
Nice, thank you so much! Merging this.

**Pull request merged**
