### PR TITLE
asterisk: reproducible builds

### PR DESCRIPTION
**Pull request by lynxis**
Remove build timestamp to make it reproducible.

### CODE REVIEW

**Comment by lynxis** [comment]
@jslachta @dangowrt

**Comment by jslachta** [comment]
@lynxis Would you be so kind to adapt the commits according to the current Makefile state? asterisk Makefiles were updated in another PR. 

Thank you.

**Comment by lynxis** [comment]
@jslachta done

**Comment by jslachta** [comment]
Thank you, Alexander @lynxis

**Pull request merged**
