### PR TITLE
freeswitch: fix compilation with musl 1.2.0

### PR DESCRIPTION
**Pull request by neheb**
Maintainer: @micmac1 
Compile tested: ath79

### CODE REVIEW

**Comment by micmac1** [comment]
Hi all,

Thanks for this. Will need to wait a bit, though. In my opinion it doesn't make sense to merge musl 1.2 fixes before it hits OpenWrt master.

Have a good weekend!
Seb

**Comment by neheb** [comment]
OTOH this is a very tiny patch.

musl 1.2 will take a while. Upstream wants to wait until after the next release.

**Comment by micmac1** [comment]
If this patch went into upstream first I'd have no problem applying it. :-)

**Comment by neheb** [comment]
https://github.com/signalwire/freeswitch/pull/921

**Comment by micmac1** [comment]
Thanks, much obliged!

**Comment by neheb** [comment]
Merged a while ago upstream.

**Comment by micmac1** [comment]
Thanks!

**Pull request merged**
