### PR TITLE
siproxd: update to version 0.8.3, improve logging and memory usage

### PR DESCRIPTION
**Pull request by guidosarducci**
**Maintainer**: @jslachta 
**Compile tested**: malta/mips_24kc/master & ea6350v3/ipq40xx/19.07.3
**Run tested**: malta/mips_24kc/master & ea6350v3/ipq40xx/19.07.3

**Description**:
This release includes bug fixes and improvements accumulated over the last
4 years of development snapshots [1].

Bump upstream version, build new plugins 'stats' and 'blacklist', and add
an 'sqlite3' package dependency for siproxd-mod-blacklist.

Disable procd capturing stderr to syslog, since siproxd in 'foreground'
mode writes both to syslog and stderr, duplicating log messages.

Include a patch to drastically reduce memory usage (RSS from 17MB to 5MB
on ipq40xx platform):

  * 005-reduce-rtpproxy-urlmap-size.patch

Drop the following patches now included upstream:

  * 010-syslog-msg.patch
  * 020-gcc10.patch
  * 100-musl-compat.patch

[1] http://siproxd.sourceforge.net/index.php?op=changelog.

Signed-off-by: Tony Ambardar <itugrok@yahoo.com>

### CODE REVIEW

**Comment by micmac1** [comment]
After all this time a new release :-) Looks good, Tony, thanks!

Am September 5, 2020 5:41:32 AM UTC schrieb guidosarducci <notifications@github.com>:
>**Maintainer**: @jslachta 
>**Compile tested**: malta/mips_24kc/master &amp; ea6350v3/ipq40xx/19.07.3
>**Run tested**: malta/mips_24kc/master &amp; ea6350v3/ipq40xx/19.07.3
>
>**Description**:
>This release includes bug fixes and improvements accumulated over the last
>4 years of development snapshots [1].
>
>Bump upstream version, build new plugins &#39;stats&#39; and &#39;blacklist&#39;, and add
>an &#39;sqlite3&#39; package dependency for siproxd-mod-blacklist.
>
>Disable procd capturing stderr to syslog, since siproxd in &#39;foreground&#39;
>mode writes both to syslog and stderr, duplicating log messages.
>
>Include a patch to drastically reduce memory usage (RSS from 17MB to 5MB
>on ipq40xx platform):
>
>  * 005-reduce-rtpproxy-urlmap-size.patch
>
>Drop the following patches now included upstream:
>
>  * 010-syslog-msg.patch
>  * 020-gcc10.patch
>  * 100-musl-compat.patch
>
>[1] http://siproxd.sourceforge.net/index.php?op=changelog.
>
>Signed-off-by: Tony Ambardar &lt;itugrok@yahoo.com&gt;
>
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/openwrt/telephony/pull/567
>
>-- Commit Summary --
>
>  * siproxd: update to version 0.8.3, improve logging and memory usage
>
>-- File Changes --
>
>    M net/siproxd/Makefile (10)
>    M net/siproxd/files/siproxd.init (1)
>    A net/siproxd/patches/005-reduce-rtpproxy-urlmap-size.patch (19)
>    D net/siproxd/patches/010-syslog-msg.patch (20)
>    D net/siproxd/patches/020-gcc10.patch (11)
>    D net/siproxd/patches/100-musl-compat.patch (13)
>
>-- Patch Links --
>
>https://github.com/openwrt/telephony/pull/567.patch
>https://github.com/openwrt/telephony/pull/567.diff
>

**Comment by guidosarducci** [comment]
> After all this time a new release :-) Looks good, Tony, thanks! 
>
Yes, a little unexpected. I had pinged the author about getting a stable snapshot download link for packaging, and he kindly decided to cut a new stable release!

BTW, I'm curious about your opinion in one area. I reduced memory usage back down to levels from siproxd 0.8.2 by using it's limits on registered client UAs (which is 128):
>Include a patch to drastically reduce memory usage (RSS from 17MB to 5MB
on ipq40xx platform):
>- 005-reduce-rtpproxy-urlmap-size.patch

Even 128 SIP UAs behind siproxd seems quite large for an embedded/home/small network use case, and I've personally been testing siproxd limited to 64 clients without a problem, further reducing RSS from 5MB down to 3MB. What do you think is a reasonable minimum number of clients to support? Even 32 would seem OK, given that siproxd could still be recompiled for special enterprise-sized use cases.

I also noticed the upstream author has on their TODO list to make this sizing configurable, but absent that has simply set large limits.

**Comment by micmac1** [comment]
Hi Tony,

I'd say that if siproxd 0.8.2 had a limit of 128 it's sensible to keep it that way. Nobody has complained about 128 as far as I know.

Reducing it even further, to 64, maybe sensible for a normal OpenWrt setup, I agree. But then maybe add a menuconfig switch so that it can be changed on the fly by the users, without having to edit the patch. I'd probably use "sed" in the Makefile to change the numbers in src/siproxd.h.

Regards,
Seb

**Review by jslachta — APPROVED** [review]
Thank you so much! Compile and run tested. Works flawlessly.

**Comment by guidosarducci** [comment]
@micmac1 Yes, I agree a menuconfig option is probably cleanest, and simpler than making it configurable in the code. Will look at this for a future update I suppose.

@jslachta Thanks for the review and testing!

**Pull request merged**
