### PR TITLE
asterisk-13.x: move package to abandoned packages

### PR DESCRIPTION
**Pull request by jslachta**
Signed-off-by: Jiri Slachta <jiri@slachta.eu>

-------------------------------

Maintainer: @jslachta 
Compile tested: not needed for package removal
Run tested: not needed for package removal

Description:

### CODE REVIEW

**Comment by jslachta** [comment]
Hi Sebastian (@micmac1), this PR removes the asterisk-13.x support from openwrt-19.07 branch. I am just letting you know about the removal we discussed before.

**Comment by micmac1** [comment]
Hello Jiri,

Thank you very much! :-)

**Comment by BKPepe** [comment]
Hi guys,

May you point me to your discussion, where you discussed the removal of Asterisk 13.x from this repo and move it to abandoned/packages?
I can find it in the commit message neither here nor https://github.com/openwrt/packages-abandoned/commit/65ddab0c24275bc7ead8697540899695b8590554.

According to [documentation](https://wiki.asterisk.org/wiki/display/AST/Asterisk+Versions) by Asterisk, the version 13.x will receive security fixes until 2020-10-24 and EOL is planned for 2021-10-24. I think it could be kept for OpenWrt 19.07 and dropped just for OpenWrt master.

**Comment by jslachta** [comment]
Hi Josef ( @BKPepe ),

it was only internal discussion about the maintenance difficulties. I understand that keeping the old package could make the overall upgrade from older openwrt versions easier where you do not have to upgrade the configuration. 

The maintenance costs grows for each openwrt release. For each release we usually had two versions of asterisk - the old one and the new one. It doubles the work only for one openwrt release. 

The reason for abandoning asterisk-13 is to reduce the overall maintenance cost to make the single asterisk package with better support, than having two packages with weaker support. We just aim to make the Asterisk package better.

Take a look at the VoIP debian team - they also have only one supported asterisk.

I hope you understand that.

Jiri

**Pull request merged**
