### PR TITLE
rtpengine: fix compilation with newer pcap

### PR DESCRIPTION
**Pull request by neheb**
This static pcap_init for some reason interferes with the function from
libpcap. Just rename it to avoid conflict.

Remove uClibc-ng patch as it's no longer in the tree.

Refresh patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @micmac1 
Compile tested: powerpc

### CODE REVIEW

**Comment by micmac1** [comment]
Am Sun, Jan 03, 2021 at 07:02:25PM -0800 schrieb Rosen Penev:
> This static pcap_init for some reason interferes with the function from
> libpcap. Just rename it to avoid conflict.

I don't see failure on bots. Please provide more details and a
reproducer. If this is really an issue then upstream would be the
correct destination for a patch I reckon.

**Comment by neheb** [comment]
Happens with a version update: http://patchwork.ozlabs.org/project/openwrt/patch/20210104234642.82529-1-rosenp@gmail.com/

**Comment by micmac1** [comment]
Am Tue, Jan 05, 2021 at 01:55:08PM -0800 schrieb Rosen Penev:
> Happens with a version update: http://patchwork.ozlabs.org/project/openwrt/patch/20210104234642.82529-1-rosenp@gmail.com/

Upstream fixed this already.
https://github.com/sipwise/rtpengine/commit/2a86d5da2ebf9777e7543a9ebe7c5b4c91f563b6

I'd rather use upstream patch.

**Comment by neheb** [comment]
7 hours ago. Of course.

**Comment by neheb** [comment]
I replaced the patch btw.

**Comment by micmac1** [comment]
Thank you!

**Pull request merged**
