### PR TITLE
asterisk: extend modules set

### PR DESCRIPTION
**Pull request by Bongo79**
Sorry i do **not** want  to merge 85 commits into master from 15.05 !
How can i send you patches only ?

Here the patches that i want to send you:
can you add asterisk13-chan-mobile [add_asterisk13-chan-mobile.patch.txt](https://github.com/openwrt/telephony/files/1502515/add_asterisk13-chan-mobile.patch.txt)

And them can you add the rest of all builded packages for Asterisk-13.x.
I use this script: [add-ast-modules.sh.txt](https://github.com/openwrt/telephony/files/1502519/add-ast-modules.sh.txt)
The result are here: [add_rest_of_modules_to_asterisk13.patch.txt](https://github.com/openwrt/telephony/files/1502522/add_rest_of_modules_to_asterisk13.patch.txt)

### CODE REVIEW

**Comment by micmac1** [comment]
Hi,

If you want chan-mobile included please provide a proper pull request for it.

Regarding "And them can you add the rest of all builded packages for Asterisk-13.x.". I hope it doesn't go unnoticed that this is a _LOT_ of work. You can't just copy and paste the output of your script. Another question is which of these modules you really _need_.

Regards,
Seb

**Comment by jslachta** [comment]
Hi @Bongo79,

as for the for-15.05 branch, I cannot add new modules, packages or features. This branch is frozen and may receive only bugfixes and security fixes. 

I cannot merge your pull request as is, however your changes won´t go unnoticed, I will add the modules you are using to the current master branch. I am keeping this ticket open until I adapt your changes to the current asterisk packages.

Thank you for your work.

**Comment by micmac1** [comment]
Hi Jiri,

I got something in the works. Please give me a little time. No need to duplicate efforts ;-)

Best regards,
Seb

Am 2. Dezember 2017 19:19:17 MEZ schrieb Jiri Slachta <notifications@github.com>:
>Hi @Bongo79,
>
>as for the for-15.05 branch, I cannot add new modules, packages or
>features. This branch is frozen and may receive only bugfixes and
>security fixes. 
>
>I cannot merge your pull request as is, however your changes won´t go
>unnoticed, I will add the modules you are using to the current master
>branch. I am keeping this ticket open until I adapt your changes to the
>current asterisk packages.
>
>Thank you for your work.

**Comment by Bongo79** [comment]
Sorry i am a noob i have no idea how can i do a proper pull request.
Is it required to fork the telefony feed to Github, modifing and send back ?
Or how is the way ?
So i will read some discription and will send a proper pull request.


> You can't just copy and paste the output of your script. Another question is which of these modules you really need.

why not ?
The idea behind them are: at the moment i do not really one module of them, 
but when people like me want to execute some Asterisk howtos, 
they have an 50% chance that the are missed some modules and them they must start to compile asterisk by SDK.
This is a lot of time and sucks. For this reason it is better when all binarys exist in a, non perfect or buggi module, as when they are not exist.
But it is only my opinion, of course the decision is yours.
For this reason i think it is a good solution to have two lists with modules on the Asterisk Makefile one with well tested and ordered modules and one with the rest of binarys and config files.

**Comment by jslachta** [comment]
Hi @Bongo79,

Sebastian (@micmac1 ) has extended the modules set. If you need any other module, please ping me or Sebastian. Please review the modules set and if it is not sufficient, please create a ticket with a set of modules you want.

Thank you.

Kind regards,
Jiri

**Pull request closed without merging**
