### PR TITLE
chan-lantiq: pull the source from github

### PR DESCRIPTION
**Pull request by micmac1**
Hello Jiri @jslachta and @kochstefan 

This PR contains also a version bump, so this is the below plus Stefan's PR #203.

Kind regards,
Sebastian

Instead of using local copies pull the source from github. The source
version is selected via CHAN_LANTIQ_VERSION, so there can be a different
version for each VARIANT.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

### CODE REVIEW

**Comment by micmac1** [comment]
Hello Jiria @jslachta 

Do you mean that a variant for asterisk15 should be in there (so another CHAN_LANTIQ_VERSION for asterisk15)? I tried to add a variant for asterisk15 but it didn't compile. Maybe @kochstefan can chime in. I tried with the master branch of chan-lantiq (there's no branch for asterisk15) but got a an error about a define not being set that asterisk15 expects. I added the define and then the build failed somewhere else. So I think that chan-lantig is not yet ready for asterisk15.

Kind regards,
Seb

**Comment by jslachta** [comment]
The only meaning of my comment was to have version declaration for each **supported** asterisk version among other declarations, something like this:

```
PKG_NAME:=chan-lantiq
PKG_VERSION:=20171111
PKG_RELEASE:=1

LANTIQ_AST13_VERSION:=5adf3d7774a75c88835f2f3daf824e2cda2c6e67

...

ifeq ($(BUILD_VARIANT),asterisk13)
CHAN_LANTIQ_AST_INCLUDES:=-I$(STAGING_DIR)/usr/include/asterisk-13/include
CHAN_LANTIQ_VERSION:=$(LANTIQ_AST13_VERSION)
endif
```

This is just a cosmetic change,.

**Comment by micmac1** [comment]
Ah, OK, will do that later today.

Am 23. November 2017 10:01:25 MEZ schrieb Jiri Slachta <notifications@github.com>:
>The only meaning of my comment was to have version declaration for each
>**supported** asterisk version among other declarations, something like
>this:
>
>```
>PKG_NAME:=chan-lantiq
>PKG_VERSION:=20171111
>PKG_RELEASE:=1
>
>LANTIQ_AST13_VERSION:=5adf3d7774a75c88835f2f3daf824e2cda2c6e67
>
>...
>
>ifeq ($(BUILD_VARIANT),asterisk13)
>CHAN_LANTIQ_AST_INCLUDES:=-I$(STAGING_DIR)/usr/include/asterisk-13/include
>CHAN_LANTIQ_VERSION:=$(LANTIQ_AST13_VERSION)
>endif
>```
>
>This is just a cosmetic change,.

**Comment by micmac1** [comment]
Ok, it's changed. Thanks for the tip!

**Comment by jslachta** [comment]
Thanks!

**Pull request merged**
