### PR TITLE
freeswitch-stable: Add compatiblity w/ openssl 1.1

### PR DESCRIPTION
**Pull request by cotequeiroz**
Maintainer: @micmac1 
Compile tested: brcm47xx/ramips, openwrt master
Run tested: I have not run tested this.

Description:
This patch was based on the current master branch, even though it is not a straight backport.
I've tripled-checked the patch, and it compiles fine, but **it needs to be run tested**.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by micmac1** [comment]
Hello @cotequeiroz 

Thank you for your work. However I'm inclined to not merge this pull request. The difference to current FS master is quite big it seems. I will not pretend that I could review these differences myself. I'm not going to merge crypto changes that upstream didn't review and accept.

Currently I'm thinking that when OpenSSL 1.1 goes into openwrt trunk I'll either cherry pick patches from FS master or temporarily switch to a FS 1.8 snapshot until upstream releases 1.8.

Kind regards,
Seb

**Comment by cotequeiroz** [comment]
Hi Seb

I understand and agree with your concerns.

I have added some comments that will make it easier to understand the patch.  I don't mean to force you to review any of this, but it may be helpful for other people as well.  Notice that I've tried to do what you first outlined above:  cherry picking patches from master.

I will try to submit the patch upstream, but I'm not sure they'll add add it to the 1.6 series.  Hopefully, they'll review it and we can move on here.

Cheers,

Eneas

**Comment by cotequeiroz** [comment]
I've sent the patch upstream.  It's here, if you want to track it:
https://freeswitch.org/jira/browse/FS-11192

**Comment by micmac1** [comment]
Hello Eneas,

Super, much obliged!

Regards,
Seb

**Comment by micmac1** [comment]
Hello Eneas,

Thanks again, also for sending the patches upstream.

Please consider closing this pull request, now that FS 1.8 is in master.

Kind regards,
Seb

**Comment by cotequeiroz** [comment]
Sure.

**Pull request closed without merging**
