### PR TITLE
build: Add CircleCI

### LINKED ISSUE #442: Add CircleCI or any other CI
I think it will be really useful if there CircleCI or any other CI is added to this repository for pull requests. From build logs, we can see that packages are compiled.

CircleCI has a free plan, which should be enough. It is used in openwrt/packages and recently it was added also to openwrt/luci.

### PR DESCRIPTION
**Pull request by BKPepe**
**Description:**

This adds [CircleCI](https://circleci.com/) from [packages repository](https://github.com/openwrt/packages) in the same state, which is there. Fixes #442 
It will give you an opinion to avoid, for example, mistakes with broken patches and provides you insights that it is compiled against the ath79 target. It will also check that each contributor has proper Signed-off-by and that the commit message starts with the prefix of the package name.

The CircleCI is being used in packages and luci repositories. There is also a possibility to use [Travis CI](https://travis-ci.org/), which is also free for open source projects, but if I remember correctly there were some false-positives, but it's up to you. I can add it as well as I am using it for packages. As if you are going to have enabled Circle CI in your (personal) fork, then there is some kind of error when you want to send a pull request to upstream as the check is gone. Anyway, two CI are still better than none and anyone can choose which CI prefers. I see that some projects for OpenWrt are using Github Actions as CI, but I have not tested it.

This was tested in my repository:  https://github.com/BKPepe/telephony/tree/circle_ci
You can check it on this commit: 
https://github.com/BKPepe/telephony/commit/019232528ea510a62896a1fdd436c7723e757b35
and build logs on Circle CI:
https://circleci.com/gh/BKPepe/telephony

After merging this pull request, you need to go to https://circleci.com/gh/openwrt/telephony/edit and follow the project to get it working.

### CODE REVIEW

**Comment by BKPepe** [comment]
Any progress here?

**Comment by jslachta** [comment]
@BKPepe, I am sorry for the silence. I am going to merge this really soon. 

Thank you for your work.

**Comment by jslachta** [comment]
@BKPepe, ack from me.

**Comment by jslachta** [comment]
Dear OpenWrt owners (at least three of you, since there is no group to ping - @blogic, @jow- , @hauke),

we want to join other repositories having continuous integration. 

Please, would you be so kind as to authorize CircleCI for this repository?  

Thank you.

**Pull request merged**
