### PR TITLE
rtpengine: fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @micmac1 
Compile tested: ath79

### CODE REVIEW

**Comment by micmac1** [comment]
Hi Rosen,

Please ping upstream for this first.

Kind regards,
Seb

**Comment by neheb** [comment]
https://github.com/sipwise/rtpengine/pull/1057

**Comment by neheb** [comment]
They merged.

**Comment by micmac1** [comment]
Thanks!

**Pull request merged**
