### PR TITLE
freeswitch-mod-mosquitto: new package

### LINKED ISSUE #655: net/freeswitch: support for mod_mosquitto
Maintainer: Sebastian Kemper <sebastian_ml@gmx.net>
Environment:
  - arch: x86_64
  - model: generic
  - version: openwrt-21.02

Description:

Trying to patch freeswitch to include support for mod_mosquitto results in the following compiler error:

```sh
In file included from mosquitto_mosq.c:40:0:
mosquitto_mosq.h:41:23: fatal error: mosquitto.h: No such file or directory
 #include "mosquitto.h"
                       ^
compilation terminated.
Makefile:670: recipe for target 'mod_mosquitto_la-mosquitto_mosq.lo' failed
```

I'll add more notes as I go along, but the first change that stands out is this line in the `.config` file:

```
CONFIG_PACKAGE_freeswitch-mod-mosquitto=y
```

Reference(s):
- https://github.com/freeswitch/mod_mosquitto

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: ?
Compile tested: ath79
Run tested: N/A

Description:
Closes #655 

Hello @oxr463

Please try this. If it works and you run-test this successfully we can add the package. If you want I can add you as maintainer. I don't really want to be the maintainer of this package as I don't use it. So I will not runtest this.

Regards,
Seb

### CODE REVIEW

**Comment by oxr463** [comment]
I'll test it and let you know how it works. I would gladly maintain it if it does work.

In my `feeds.conf` file:
```
src-git telephony https://github.com/micmac1/telephony;mqtt
```

**Comment by micmac1** [comment]
Does it run? You'll find the package somewhere in bin/packages, the you can install it and try it out.

Am July 16, 2021 1:05:01 PM UTC schrieb Lucas Ramage ***@***.***>:
***@***.*** approved this pull request.
>
>I was successfully able to compile:
>
>```sh
>file build_dir/target-x86_64_musl/freeswitch-mod-mosquitto-2021-01-15-b7b859a9/ipkg-x86_64/freeswitch-mod-mosquitto/usr/lib/freeswitch/mod/mod_mosquitto.so
>```
>
>
>

**Comment by oxr463** [comment]
> Does it run? You'll find the package somewhere in bin/packages, the you can install it and try it out. Am July 16, 2021 1:05:01 PM UTC schrieb Lucas Ramage ***@***.***>: ***@***.*** approved this pull request.
> […](#)
> I was successfully able to compile: ```sh file build_dir/target-x86_64_musl/freeswitch-mod-mosquitto-2021-01-15-b7b859a9/ipkg-x86_64/freeswitch-mod-mosquitto/usr/lib/freeswitch/mod/mod_mosquitto.so ```

Hi @micmac1. I haven't forgotten about this. It's just been a little busy recently.

**Comment by micmac1** [comment]
No rush, take your time. We can reopen.

**Pull request closed without merging**
