### PR TITLE
net/asterisk-11.x: Bump again to 11.17.1 (cross compile fix included)

### PR DESCRIPTION
**Pull request by micmac1**
Hello,

This includes a fix from upstream for the cross compile failure.

### CODE REVIEW

**Comment by jslachta** [comment]
Tested, thanks.

**Comment by jslachta** [comment]
Would you be so kind to sign-off-by your commit?

**Comment by micmac1** [comment]
Not 100% sure but the sign-off should be included now. Please check.

**Comment by jslachta** [comment]
The last things from me:
- please squash commits into one - https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/
- set PKG_RELEASE:=1

Otherwise it is ok. I tested it and it works. When you fix the things I mentioned, I am ready to merge your PR.

**Comment by micmac1** [comment]
Hi, thanks for the tip. Looks much nicer this way.

**Pull request merged**
