### PR TITLE
<net/asterisk-chan-sccp>: Update to v4.3.2-epsilon

### PR DESCRIPTION
**Pull request by dkgroot**
Maintainer: Diederik de Groot / @<dkgroot>
Compile tested: No Tested (TBH)
Run tested: Running previous version on OpenWrt 18.06.4

Description:
Just a version bump. Don't  have the full openwrt crosscompile stack available for testing/running. Sorry for that, i was hoping there would be some kind of CI, to take care of that.

### CODE REVIEW

**Comment by dkgroot** [comment]
I removed the previous gcc8 patches, which should have already been fixed upstream (See: #425)

**Comment by micmac1** [comment]
Hello @dkgroot 

Thanks for the pull request! Compile-tested on a master checkout from a few days ago. For both an ath79 target (gcc 7.x) and arc (gcc 8.3).

Could you please set the version to a number? It should be a number, otherwise there will be problems with the upgrade path (what's bigger/newer, "v4.3.2-20190411" or "v4.3.2-epsilon"?). opkg won't be able to handle that properly. And PKG_RELEASE should be reset to "1".

Suggestion below (with corrected PKG_MIRROR_HASH). For version I used 20190730 as the specified commit is from yesterday.

```
--- a/net/asterisk-chan-sccp/Makefile
+++ b/net/asterisk-chan-sccp/Makefile
@@ -9,14 +9,14 @@
 include $(TOPDIR)/rules.mk

 PKG_NAME:=chan-sccp
-PKG_VERSION:=v4.3.2-20190411
-PKG_RELEASE:=2
+PKG_VERSION:=v4.3.2-20190730
+PKG_RELEASE:=1

 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
 PKG_SOURCE_URL:=https://github.com/chan-sccp/chan-sccp.git
 PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
-PKG_SOURCE_VERSION:=da59f2f073502645b34b458392a1fb11465f48cc
-PKG_MIRROR_HASH:=a449c3384b92ff79b2db4d6b4e8dc7a3fb668f4c0f1a65baa198578b0b953ab8
+PKG_SOURCE_VERSION:=08c9457b131e2e7fea92b2dfea786abfd171a5fe
+PKG_MIRROR_HASH:=be86af36c2ba4524d392fab1b88e4f4ceaaea6678dd814443ae5636337ed4c77
 PKG_SOURCE_PROTO:=git

 PKG_FIXUP:=autoreconf
```

**Comment by micmac1** [comment]
Thanks again!

I added Jiri as reviewer.

**Comment by dkgroot** [comment]
Super !

BTW: I noticed on the right side that i left 'allow edits from maintainers' switched on, so you could have alter the PR with your changes, without going through me. Then again it's good to know how i should make a similar PR next time. 

Having to maintain multiple packaging methods can be a bit daunting to be honest. Someone should just figure out a single packaging method for any and all platforms allready  :-)

BTW: Hi Jiri, hope you are doing well, haven't heard from you in a while :-)

**Comment by micmac1** [comment]
Oh, can you please squash the two commits into one? Something like this:

```
git reset HEAD~2
git commit -s -m "..."
git commit --amend
git push -f
```

**Comment by dkgroot** [comment]
@micmac1 thanks for the help and doing the checking/testing for me BTW ! Much appreciated

**Comment by jslachta** [comment]
Compile and run tested. Thanks to both of you, @dkgroot, @micmac1 !

**Pull request merged**
