### PR TITLE
asterisk: bump to 18.5.1

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: @jslachta 
Compile tested: master + 19.07 ath79
Run tested: 19.07 ath79

Description: Hi Jiri,

Minor bump + dep update + pjproject patch sync

Kind regards,
Seb

### CODE REVIEW

**Comment by dhewg** [comment]
Thanks, seems to work just fine for me!

**Comment by micmac1** [comment]
Hi there @dhewg

If I'm not mistaken you're using lantiq. Do you use the phone ports and experience call releases with chan-lantiq when you press digits/DTMF, like reported in issue #631? I'm curious.

Kind regards,
Seb

**Comment by dhewg** [comment]
Hi @micmac1,

nope, while indeed on lantiq arch, I'm not using chan-lantiq. I ran into the related #597 tough

**Comment by micmac1** [comment]
But not anymore, right?

**Comment by dhewg** [comment]
Correct, that was fixed with installing/depending on the timerfd asterisk module

**Comment by micmac1** [comment]
Thanks!

**Comment by jslachta** [comment]
Ack, compile and run tested.

Thank you, Sebastian!

**Comment by jospezial** [comment]
@micmac1 
Please add PATCH 2/2 for
https://github.com/openwrt/telephony/blob/master/libs/pjproject/patches/0110-tls-parent-listener-destroyed.patch
See
https://github.com/dhewg/telephony/commit/501e539157e084f4cb09a1d9ee5bfae67c47d059
"pjproject: add missing patch from AST-2021-009
There are two related patches and only one was added."

Or a version bump to https://github.com/pjsip/pjproject/releases/tag/2.11.1 which contains this fix?

If I take a look at
https://github.com/pjsip/pjproject/security/advisories
there are some recent security vulnerabilities which are fixed in
https://github.com/pjsip/pjproject/commits/master

**Comment by micmac1** [comment]
> Please add PATCH 2/2 for
> https://github.com/openwrt/telephony/blob/master/libs/pjproject/patches/0110-tls-parent-listener-destroyed.patch

Thanks for bringing this up. Added to both master and 21.02. 19.07
already had it.

**Pull request merged**
