### PR TITLE
libs/dahdi-linux: bump to latest git head

### PR DESCRIPTION
**Pull request by aduskett**
Fixes compiling against linux >= 6.6

Maintainer: me 
Compile tested: main branch
Run tested: no

Description: Fixes compiling against kernel >= 6.6

### CODE REVIEW

**Comment by micmac1** [comment]
Hi Adam,

This looks fine in general. Two things:

1) PKG_RELEASE should be set to 1 after a bump
2) Compile fails at some point. I tested this in the ath79 snapshot SDK:

```
  HOSTCC  /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/xpp/print_fxo_modes.o
  HOSTLD  /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/xpp/print_fxo_modes
  GEN     /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/xpp/init_fxo_modes
  CHECK   /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/xpp/init_card_2_30
  CC [M]  /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200/base.o
/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200/base.c: In function 'wctdm_transmitprep':
/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200/base.c:467:32: error: unused variable 'pos' [-Werror=unused-variable]
  467 |         int x, y, chan_offset, pos;
      |                                ^~~
/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200/base.c:467:13: error: unused variable 'x' [-Werror=unused-variable]
  467 |         int x, y, chan_offset, pos;
      |             ^
/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200/base.c: In function 'wctdm_receiveprep':
/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200/base.c:556:16: error: unused variable 'y' [-Werror=unused-variable]
  556 |         int x, y, chan_offset;
      |                ^
cc1: all warnings being treated as errors
make[6]: *** [scripts/Makefile.build:250: /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200/base.o] Error 1
make[5]: *** [scripts/Makefile.build:500: /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi/opvxa1200] Error 2
make[4]: *** [Makefile:2010: /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/drivers/dahdi] Error 2
make[4]: Leaving directory '/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-6.1.82'
make[3]: *** [Makefile:74: modules] Error 2
make[3]: Leaving directory '/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64'
make[2]: *** [Makefile:111: /home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-mips_24kc_musl/linux-ath79_generic/dahdi-linux-2024.04.12~83d89b64/.built] Error 2
make[2]: Leaving directory '/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-13.2.0_musl.Linux-x86_64/feeds/telephony/libs/dahdi-linux'
time: package/feeds/telephony/dahdi-linux/compile#39.68#3.57#48.97
    ERROR: package/feeds/telephony/dahdi-linux failed to build.
make[1]: *** [package/Makefile:129: package/feeds/telephony/dahdi-linux/compile] Error 1
```

I'll active the workflows now, to check how far they go.

**Comment by micmac1** [comment]
The tests complain about dirty patches. So please:

1. Update PKG_RELEASE to 1 in libs/dahdi-linux/Makefile
2. Refresh patches: `make package/dahdi-linux/refresh V=s`
3. Add a patch to turn the unused-variable error into a warning:

```
cat feeds/telephony/libs/dahdi-linux/patches/207-opvxa1200-unused-variable.patch 
--- a/drivers/dahdi/opvxa1200/Kbuild
+++ b/drivers/dahdi/opvxa1200/Kbuild
@@ -1,6 +1,6 @@
 obj-$(DAHDI_BUILD_ALL)$(CONFIG_DAHDI_OPVXA1200) += opvxa1200.o
 
-EXTRA_CFLAGS += -I$(src)/.. -Wno-undef
+EXTRA_CFLAGS += -I$(src)/.. -Wno-undef -Wno-error=unused-variable
 
 opvxa1200-objs := base.o
```

**Comment by aduskett** [comment]
Thanks for the tips @micmac1 ! I am pretty sure everything is fixed now. The autobuilders will soon tell!

**Comment by micmac1** [comment]
Yes, I think we need to update our github actions scripts to whatever the package repo has (again).

Anyway, thanks for this! Have a good weekend!

Kind regards,
Seb

**Pull request merged**
