### PR TITLE
New PR: asterisk segfault and freeswitch

### PR DESCRIPTION
**Pull request by micmac1**
Hello Jiri @jslachta 

This includes a fix for the Asterisk segfault in issue #173 as well as some benign Freeswitch changes.

Thank you!

Best regards,
Sebastian

### CODE REVIEW

**Comment by jslachta** [comment]
Thank you, Sebastian. I am currently investigating, why LOW_MEMORY does not work.

**Comment by jslachta** [comment]
I am going to bump PKG_RELEASE variable for both asterisk packages.

**Comment by micmac1** [comment]
Morning Jiri,

Super, much obliged!

Regards,
Seb

Am 4. August 2017 08:00:56 MESZ schrieb Jiri Slachta <notifications@github.com>:
>I am going to bump PKG_RELEASE variable for both asterisk packages.

**Comment by micmac1** [comment]
Just one thing I'd like to add. Google search for LOW_MEMORY has a lot of results with many problems reported. There are also tickets at upstream that were not resolved due to lack of feedback etc. There's also Freetz, a distro for AVM Fritz boxes, and they, too, disable it by default, referring to known problems.

I think the flag doesn't get too much testing, because it's disabled by default. So maybe you don't want to waste too much energy on this.

Just my 2 cents.

Regards,
Seb

Am 4. August 2017 08:03:24 MESZ schrieb Sebastian Kemper <sebastian_ml@gmx.net>:
>Morning Jiri,
>
>Super, much obliged!
>
>Regards,
>Seb
>
>Am 4. August 2017 08:00:56 MESZ schrieb Jiri Slachta
><notifications@github.com>:
>>I am going to bump PKG_RELEASE variable for both asterisk packages.

**Comment by urobasa** [comment]
Thank you!

Best regards,
SST_Fanat

**Pull request merged**
