### PR TITLE
libks: fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @micmac1 
Compile tested: ath79

### CODE REVIEW

**Comment by micmac1** [comment]
Hi Rosen,

This should go upstream first, to get a proper review and (hopefully) get commited, so that it then can trickle down to the downstream.

I'm not sure what your expectation here is. Do you expect me to blindly commit this or do you expect that I take it upstream?

Kind regards,
Seb

**Comment by neheb** [comment]
The former.

**Comment by micmac1** [comment]
I'd have to decline. I think it's too risky to take these changes lightly. They should be properly reviewed by somebody who understands the patches. This should be done upstream.

**Comment by neheb** [comment]
Looking at this patchset, it's just missing headers, getm* API rename, and removal of explicit initialization/deinitialization. The last one is completely deprecated as it is already done internally.

I submitted it anyway: https://github.com/signalwire/libks/pull/81

**Comment by neheb** [comment]
This was merged upstream.

**Comment by micmac1** [comment]
Thanks!

**Pull request merged**
