### PR TITLE
dahdi-tools: remove glibc specific DECLS

### PR DESCRIPTION
**Pull request by neheb**
Fixes compilation with musl 1.2.0 and above.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @VittGam 
Compile tested: ath79

### CODE REVIEW

**Comment by neheb** [comment]
ping @openwrt/telephone-maintainers

**Comment by micmac1** [comment]
> ping @openwrt/telephone-maintainers

This looks like something that is not specific to OpenWrt and should go upstream. Have you already send it there?

**Comment by neheb** [comment]
Upstream seems dead

**Comment by micmac1** [comment]
> Upstream seems dead

Upstream is asterisk project. I doubt they're dead.

**Comment by neheb** [comment]
Sure but last commit from 2018.

**Comment by micmac1** [comment]
It doesn't mean they're dead. DAHDI is definitely not fast-paced, it's about legacy hardware IMHO. There's is a dahdi-linux/next branch with commits from this year. I don't think they accept PRs via github. Probably they would require that you submit patches via the same mechanism that one would use for asterisk itself ([Link](https://wiki.asterisk.org/wiki/display/AST/Patch+Contribution+Process)). It's a bit tedious to do (speaking from experience).

I could understand if you would not want to bother with this. In that case I'd look at this myself and post a patch upstream eventually. But I'd do it after musl 1.2 is commited to OpenWrt. I don't see any urgency here.

**Pull request closed without merging**
