### PR TITLE
Number of small updates regarding chan-sccp-b and the use of realtime (sqlite3)

### PR DESCRIPTION
**Pull request by dkgroot**
The realtime modules for asterisk-11 and asterisk-13 where missing, making it harder to use the sqlite3 realtime database.

Added requsted sample files to show how to use chan-sccp-b with realtime (not active by default)

### CODE REVIEW

**Comment by jslachta** [comment]
Hello Diederik,

I would suggest to split example configuration files to separate package (asterisk18-chan-sccp-b-{config,examples,...}). 

The rest of the changes is ok.

Jiri

**Comment by dkgroot** [comment]
Hi Jiri,

I am not really sure how to do that (anymore), can you give me a hint or some help ?

BTW: we will (finally) be releasing V4.2-stable next week.

Regards,

Diederik

**Comment by dkgroot** [comment]
Version: V4.2_STABLE
=====================
New Features in V4.2
 - Enums processed using awk generation script
 - Multi channel Direct RTP (Partial)
 - Enums processed using meta programming (Renewed macro implementation)
 - Support for named callgroup / pickupgroups when using >asterisk-11
 - Added Support for Asterisk-12
 - Added Support for Asterisk-13
 - Support for IPv4 and IPv6
 - Updated/Changed DTMF Handling to always take rfc2833
 - Multi Channel Direct RTP (ie: SIP-SCCP direct media)
 - Enums processed using meta programming (Renewed macro implementation)
 - Support for named callgroup / pickupgroups when using >asterisk-11
 - Added support for earlyrtp=immediate
 - Added Scheduled Hangup (So that you can hear the hangupcause)
 - Reworked digittimeout
 - Improved sccp.conf / buttonconfig button change detection on sccp reload
 - Allow HASH() dialplan function when using SCCPDEVICE(), SCCPLINE() and SCCPCHANNEL()
 - Added Audio Quality Statistics in CHANNEL() and SCCPDEVICE() / SCCPCHANNEL)()
 - Updated hangup / queue_hangup handling
 - Support for UTF-8 config file (allowing accented characters in labels and description on older phones)
 - Improved support for none x86 systems, fixing most if not all unaligned accesses

Bug Fixes
 - Fixed Some asterisk-12 / asterisk-13 issues
 - Fixed buttontemplate instance issue
 - Fixed RTP Handling
 - Replaced Asterisk Scheduled Macro Use
 - Numerous smaller / bigger fixes (Check ChangeLog for details)

**Comment by dangowrt** [comment]
Please rebase on-top of openwrt/telephony.git's master branch instead of merging like you did in https://github.com/dkgroot/telephony/commit/8b95836da4febb190c35a871dcdaf17653436aef as that will unnecessarily polute the timeline.
The best way to stage a pull request is by creating a for-upstream branch and cherry-pick your changes there, then use git rebase -i master to squash, fixup and reword things so it will match the upstream style.

**Comment by dkgroot** [comment]
Hi Daniel, I didn't notice i had a merge in there. That was a bad idea. I will create a new pull request using a clean branch. Sorry about that one.

**Pull request closed without merging**
