### PR TITLE
asterisk-chan-sccp: update to v4.3.3 release

### PR DESCRIPTION
**Pull request by dkgroot**
Signed-off-by: Diederik de Groot <dkgroot@talon.nl>

Please double check that your commits:
- all start with "<package name>: "
- all contain signed-off-by
- are linked to your github account (you see your logo in front of them)

Please also read https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md

Thanks for your contribution
Please remove this text (before ---) and fill the following template
-------------------------------

Maintainer: me / @<github-user>
Compile tested: (put here arch, model, OpenWRT/LEDE version)
Run tested: (put here arch, model, OpenWRT/LEDE version, tests done)

Description:

### CODE REVIEW

**Comment by micmac1** [comment]
Hi @dkgroot :)

Can you please update subject line of commit for CI to pass?

It currently stops with this warning: "Commit subject line MUST start with '<package name>: ' (Update chan-sccp to v4.3.3 release)"

Correct would be: asterisk-chan-sccp: update to v4.3.3

Thanks!
Seb

P.S.: I can't fix the subject of your commit via github.

**Comment by dkgroot** [comment]
I change the PR title and amended the commit (plus forced push) but apparently circleci doesn't like it still. I don't have access to circleCI so i cannot see what it doesn't like about it.

**Comment by micmac1** [comment]
Hello @dkgroot 

Thanks! It seems the PKG_MIRROR_HASH is wrong.

```
make package/asterisk-chan-sccp/download
make package/asterisk-chan-sccp/check V=s
WARNING: PKG_MIRROR_HASH does not match asterisk-chan-sccp-2020-12-19-968caa45.tar.xz hash 627e9057a70b01d1fd69c80c0f6a138c79aace10082d76016af23a6bafd2a3d7
make package/asterisk-chan-sccp/check V=s FIXUP=1
```

Can you replace yours with 627e9057a70b01d1fd69c80c0f6a138c79aace10082d76016af23a6bafd2a3d7? That should do.

Kind regards,
Seb

**Comment by dkgroot** [comment]
Sorry it took me a couple of tries to get it to pass CircleCI checks. Somehow it did not like me using "--amend", but using a "commit +  rebase" worked. Waiting for CI

**Review by jslachta — APPROVED** [review]

**Comment by jslachta** [comment]
Looks good.  Thank you, Diederik and Sebastian!

**Pull request merged**
