### PR TITLE
asterisk-g72x: update to 1.4

### PR DESCRIPTION
**Pull request by jpap**

### CODE REVIEW

**Comment by jpap** [comment]
Tested on Asterisk 13 and works well on my Netgear R7800.

**Comment by jslachta** [comment]
@jpap, please, the PKG_RELEASE should have value 1 for the new release. Would you be so kind to modify the commit title to the prefixed one variant? Should be something like "asterisk-g72x: update to 1.4".

**Comment by jpap** [comment]
Done!

**Comment by jslachta** [comment]
Thank you!

**Pull request merged**
