### PR TITLE
siproxd: add max clients configuration and default

### PR DESCRIPTION
**Pull request by guidosarducci**
**Maintainer**: @jslachta 
**Compile tested**: malta/mips_24kc/master
**Run tested**: malta/mips_24kc/master

**Description**:
Add a configuration option SIPROXD_MAX_CLIENTS used for compile-time sizing
of the maximum supported proxy clients. Set this to a default value of 32,
which is more suitable for a small network or CPE router and uses much
less memory than the upstream value of 512 (e.g. RSS of 2 MB vs 17 MB).

Drop the following patch in favour of the new config option:

  * 005-reduce-rtpproxy-urlmap-size.patch

Also fix an incorrect configure option, and silence many warnings due to
unused VCS 'ident' variables in the sources.

Signed-off-by: Tony Ambardar <itugrok@yahoo.com>

### CODE REVIEW

**Comment by guidosarducci** [comment]
@micmac1 Hi Seb, this follows up from our recent discussion in https://github.com/openwrt/telephony/pull/567#issuecomment-687658932. Seems to work fairly well.

**Comment by micmac1** [comment]
Hi Tony, I don't use siproxd myself so I'll gladly take your word for it :-) Have a good day and thanks for your work!

**Comment by micmac1** [comment]
One small nitpick, maybe PKG_CONFIG_DEPENDS should be outside of the package definition? Maybe it works inside but usually it's set outside, no? I'll double-check tonight or tomorrow.

Am September 22, 2020 8:55:16 AM UTC schrieb guidosarducci <notifications@github.com>:
>@micmac1 Hi Seb, this follows up from our recent discussion in https://github.com/openwrt/telephony/pull/567#issuecomment-687658932. Seems to work fairly well.
>

**Comment by guidosarducci** [comment]
Hmm. Yes, I think you're right: it does work but cleaner as you suggested. Also fixed some build warnings I noticed. Thanks!

**Comment by micmac1** [comment]
Looks good to me, compiles fine. I'm wondering why spaces instead of
tabs in lines 2 and 3 of the $(ESED) command. That looks a bit weird to
me. But OK, I'm just nitpicking again :)

Thanks!

**Comment by guidosarducci** [comment]
Good catch, I'm glad someone is paying attention! 🙄  Fixed up the whitespace...

**Comment by micmac1** [comment]
Thanks a bunch!

**Review by jslachta — APPROVED** [review]

**Comment by jslachta** [comment]
Thank you, guys!

**Pull request merged**
