### PR TITLE
[21.02] yate: bump to 6.3.0 and enable speex codec

### PR DESCRIPTION
**Pull request by robho**
yate: bump to 6.3.0 and enable speex codec

New yate modules in this release:
yate-mod-ilbcwebrtc
yate-mod-speexcodec
yate-mod-wiresniff

Some patches were removed:
110-no-libnsl.patch - not needed
120-create-thread-key-on-access.patch - not needed
150-video-codecs-mapping.patch - already applied upstream

Some additional changes:
* An upstream fix (r6470) is cherry-picked to avoid crashing when YATE
  receives an invalid SIP message.

* Build directory changed to include package version.

* Set PKG_BUILD_PARALLEL to allow parallelized build of yate.

* Speed up build if yate-mod-ilbccodec or yate-mod-sqlitedb is
  disabled (disable ilbc and sqlite in configure step).

* Removing umbrella package yate-collection-basic. It isn't built and
  hasn't been built for years and I think the modules it wants to
  install are a bit strange and probably not useful to most
  users. From the name yate-collection-basic I would expect to get
  some basic functionality, but why would I then need
  yate-mod-dumbchan, yate-mod-rmanager and yate-mod-tonegen? What is
  the use case? I think it's better that users themselves install the
  packages needed for their use case, especially in OpenWrt where
  flash space usually is limited and you don't want to install more
  packages than what you really need.

I've tested basic SIP calls on a Netgear R6220 running 21.02.0-rc2.

Tested-by: Robert Högberg <robert.hogberg@gmail.com>
Signed-off-by: Robert Högberg <robert.hogberg@gmail.com>

-------------------------------

Maintainer: @jslachta
Compile tested: Netgear R6220, ramips, mipsel_24kc, openwrt-21.02
Run tested: Netgear R6220, ramips, mipsel_24kc, openwrt-21.02

### CODE REVIEW

**Comment by robho** [comment]
@micmac1, there are two patches from you that I didn't touch:
130-fix-ilbc-flags.patch
140-warning-unknown-architecture.patch

From the patches's commit messages I got the impression that the patches fix build problems, but for me yate built even without these patches. Do you know if they are still needed when building for some specific target or in some other situation?

**Comment by micmac1** [comment]
Hi Robert,

Few points from me:

1. This should go into master first (can be cherry-picked to openwrt-21.02 branch later).
2. The nls.mk include never hurts and should be kept in my opinion. Even if yate doesn't use iconv maybe some external lib it depends on will at some point.
3. Two new modules are available which can be added: g722webrtc and wiresniff.
4. A warning could be fixed ("Makefile:207: WARNING: skipping yate-collection-basic -- package has no install section").
5. The package is built in $(BUILD_DIR)/yate. If you want to compare stuff between versions this makes it harder. So building in $(BUILD_DIR)/yate-$(PKG_VERSION) would be nice.
6. The yate upstream version has a suffix with a "-". But on openwrt "-" is used to separate $(PKG_VERSION) from $(PKG_RELEASE) a la PKG_NAME-PKG_VERSION-PKG_RELEASE. But with yate's versioning we have 3 times "-". This could be amended, for instance like the suggestion below. If upstream ever updates the suffix we can just increment our PKG_RELEASE.
7. PKG_BUILD_PARALLEL:=1 could be added to speed up compiles.

```
diff --git a/net/yate/Makefile b/net/yate/Makefile
index 91fc10f..92136f8 100644
--- a/net/yate/Makefile
+++ b/net/yate/Makefile
@@ -9,13 +9,14 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=yate
-PKG_VERSION:=6.1.0-1
-PKG_RELEASE:=3
+PKG_VERSION:=6.3.0
+PKG_VERSION_SUFFIX:=1
+PKG_RELEASE:=1
 
-PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
+PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_VERSION_SUFFIX).tar.gz
 PKG_SOURCE_URL:=http://yate.null.ro/tarballs/yate6/
-PKG_HASH:=ed88519c8e2f63eec0d699bc6ed8831854af9b32b654b3d7e7c2697b528aa377
-PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)
+PKG_HASH:=cbd3afc417da7b26b4d7f57146c815a667db2bf1ff4d1ea9dae986954cbcd62f
+PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)-$(PKG_VERSION_SUFFIX)
 
 PKG_LICENSE:=GPL-2.0
 PKG_LICENSE_FILES:=COPYING
@@ -23,6 +24,7 @@ PKG_MAINTAINER:=Jiri Slachta <jiri@slachta.eu>
 
 PKG_FIXUP:=autoreconf
 
+PKG_BUILD_PARALLEL:=1
 PKG_INSTALL:=1
 
 # Yate currently does not compile with FORTIFY_SOURCE enabled
@@ -37,12 +39,15 @@ PKG_CONFIG_DEPENDS:= \
        CONFIG_PACKAGE_$(PKG_NAME)-mod-faxchan \
        CONFIG_PACKAGE_$(PKG_NAME)-mod-openssl \
        CONFIG_PACKAGE_$(PKG_NAME)-mod-zlibcompress \
+       CONFIG_PACKAGE_$(PKG_NAME)-mod-g722webrtc \
        CONFIG_SOFT_FLOAT
 
 include $(INCLUDE_DIR)/package.mk
 # Needed for yate-mod-mysqldb to find iconv
 include $(INCLUDE_DIR)/nls.mk
 
+TAR_CMD:=$(HOST_TAR) -C $(PKG_BUILD_DIR) --strip-components 1 $(TAR_OPTIONS)
+
 define Package/$(PKG_NAME)/Default
   SUBMENU:=Telephony
   SECTION:=net
@@ -107,6 +112,7 @@ CONFIGURE_ARGS+= \
        --disable-tdmcard \
        --disable-wanpipe \
        --enable-ilbc \
+       $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-g722webrtc),--enable-g722-webrtc,--disable-g722-webrtc) \
        $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-ilbcwebrtc),--enable-ilbc-webrtc,--disable-ilbc-webrtc) \
        $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-pgsqldb),--with-libpq="$(STAGING_DIR)/usr",--without-libpq) \
        $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-mysqldb),--with-mysql=yes,--with-mysql=no) \
@@ -163,6 +169,7 @@ define Package/$(PKG_NAME)-sounds/install
 endef
 
 define Package/$(PKG_NAME)-collection-basic/install
+       true
 endef
 
 define Build/InstallDev
@@ -244,6 +251,7 @@ $(eval $(call BuildPlugin,extmodule,,External Module Handler,,/usr/share/yate/sc
 $(eval $(call BuildPlugin,faxchan,,Spandsp Fax Channel,+libspandsp))
 $(eval $(call BuildPlugin,fileinfo,,File Info Holder,,,y))
 $(eval $(call BuildPlugin,filetransfer,,File Transfer Driver,,,y))
+$(eval $(call BuildPlugin,g722webrtc,,G.722 codec using library based on WebRTC project,,,))
 $(eval $(call BuildPlugin,gvoice,,Google Voice support,,,y))
 $(eval $(call BuildPlugin,heartbeat,server,Linux-HA compatible heartbeat,,,y))
 $(eval $(call BuildPlugin,ilbccodec,,iLBC Codec,))
@@ -287,6 +295,7 @@ $(eval $(call BuildPlugin,tonedetect,,Detectors for Various Tones,))
 $(eval $(call BuildPlugin,tonegen,,Tones Generator,,,y))
 $(eval $(call BuildPlugin,users,server,Users,,,y))
 $(eval $(call BuildPlugin,wavefile,,Wav file Record and Playback,))
+$(eval $(call BuildPlugin,wiresniff,,Capture interface for YATE messages,,,y))
 $(eval $(call BuildPlugin,wpcard,server,Wanpipe PRI cards Signalling and Data Driver,@BROKEN)) # Mising wanpipe and PRI libraries
 $(eval $(call BuildPlugin,yiaxchan,,IAX Channel,,,y))
 $(eval $(call BuildPlugin,yjinglechan,,Jingle Channel,,,y))
```

**Comment by micmac1** [comment]
Hi @robho, I received another mail form github where you asked about two other patches. Unfortunately I don't find this here.

Anyway, 130-fix-ilbc-flags.patch is there to prevent ilbc from adding extra CFLAGS and overriding openwrt cflags. Without the patch it adds "-O3 -funroll-loops -fomit-frame-pointer" to the end of the command. So this should stay.

140-warning-unknown-architecture.patch was added in commit 489adca0dbea894920b36a5e6e0400f563a87ae0 to allow building on arc and aarch64. The included typedefs.h file was last edited in 2017, so nothing changed. Patch should be kept as well.

Kind regards,
Seb

P.S.: I'm not sure why you sent the pull request for 21.02 instead of master. Maybe because you're running 21.02 on your router. If you open a pull request for master and write that you tested this on 21.02 that's fine in my book. I don't have multiple routers and I run 19.07 and test there. I don't have time to change around openwrt releases on my router to test on all the different branches.

**Comment by micmac1** [comment]
I was browsing snapshot packages and realized that packages that use PKG_SOURCE_DATE also have dashes in what is used as their "PKG_VERSION". For example: asterisk-codec-opus_2017-10-09-83e1b458-1_mipsel_24kc.ipk

So what I wrote about openwrt using the "-" doesn't seem to make much sense. So I'd drop the suffix handling suggestion :)

```
diff --git a/net/yate/Makefile b/net/yate/Makefile
index 91fc10f..9caa8e3 100644
--- a/net/yate/Makefile
+++ b/net/yate/Makefile
@@ -9,13 +9,13 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=yate
-PKG_VERSION:=6.1.0-1
-PKG_RELEASE:=3
+PKG_VERSION:=6.3.0-1
+PKG_RELEASE:=1
 
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
 PKG_SOURCE_URL:=http://yate.null.ro/tarballs/yate6/
-PKG_HASH:=ed88519c8e2f63eec0d699bc6ed8831854af9b32b654b3d7e7c2697b528aa377
-PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)
+PKG_HASH:=cbd3afc417da7b26b4d7f57146c815a667db2bf1ff4d1ea9dae986954cbcd62f
+PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)
 
 PKG_LICENSE:=GPL-2.0
 PKG_LICENSE_FILES:=COPYING
@@ -23,6 +23,7 @@ PKG_MAINTAINER:=Jiri Slachta <jiri@slachta.eu>
 
 PKG_FIXUP:=autoreconf
 
+PKG_BUILD_PARALLEL:=1
 PKG_INSTALL:=1
 
 # Yate currently does not compile with FORTIFY_SOURCE enabled
@@ -37,12 +38,15 @@ PKG_CONFIG_DEPENDS:= \
        CONFIG_PACKAGE_$(PKG_NAME)-mod-faxchan \
        CONFIG_PACKAGE_$(PKG_NAME)-mod-openssl \
        CONFIG_PACKAGE_$(PKG_NAME)-mod-zlibcompress \
+       CONFIG_PACKAGE_$(PKG_NAME)-mod-g722webrtc \
        CONFIG_SOFT_FLOAT
 
 include $(INCLUDE_DIR)/package.mk
 # Needed for yate-mod-mysqldb to find iconv
 include $(INCLUDE_DIR)/nls.mk
 
+TAR_CMD:=$(HOST_TAR) -C $(PKG_BUILD_DIR) --strip-components 1 $(TAR_OPTIONS)
+
 define Package/$(PKG_NAME)/Default
   SUBMENU:=Telephony
   SECTION:=net
@@ -107,6 +111,7 @@ CONFIGURE_ARGS+= \
        --disable-tdmcard \
        --disable-wanpipe \
        --enable-ilbc \
+       $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-g722webrtc),--enable-g722-webrtc,--disable-g722-webrtc) \
        $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-ilbcwebrtc),--enable-ilbc-webrtc,--disable-ilbc-webrtc) \
        $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-pgsqldb),--with-libpq="$(STAGING_DIR)/usr",--without-libpq) \
        $(if $(CONFIG_PACKAGE_$(PKG_NAME)-mod-mysqldb),--with-mysql=yes,--with-mysql=no) \
@@ -163,6 +168,7 @@ define Package/$(PKG_NAME)-sounds/install
 endef
 
 define Package/$(PKG_NAME)-collection-basic/install
+       true
 endef
 
 define Build/InstallDev
@@ -244,6 +250,7 @@ $(eval $(call BuildPlugin,extmodule,,External Module Handler,,/usr/share/yate/sc
 $(eval $(call BuildPlugin,faxchan,,Spandsp Fax Channel,+libspandsp))
 $(eval $(call BuildPlugin,fileinfo,,File Info Holder,,,y))
 $(eval $(call BuildPlugin,filetransfer,,File Transfer Driver,,,y))
+$(eval $(call BuildPlugin,g722webrtc,,G.722 codec using library based on WebRTC project,,,))
 $(eval $(call BuildPlugin,gvoice,,Google Voice support,,,y))
 $(eval $(call BuildPlugin,heartbeat,server,Linux-HA compatible heartbeat,,,y))
 $(eval $(call BuildPlugin,ilbccodec,,iLBC Codec,))
@@ -287,6 +294,7 @@ $(eval $(call BuildPlugin,tonedetect,,Detectors for Various Tones,))
 $(eval $(call BuildPlugin,tonegen,,Tones Generator,,,y))
 $(eval $(call BuildPlugin,users,server,Users,,,y))
 $(eval $(call BuildPlugin,wavefile,,Wav file Record and Playback,))
+$(eval $(call BuildPlugin,wiresniff,,Capture interface for YATE messages,,,y))
 $(eval $(call BuildPlugin,wpcard,server,Wanpipe PRI cards Signalling and Data Driver,@BROKEN)) # Mising wanpipe and PRI libraries
 $(eval $(call BuildPlugin,yiaxchan,,IAX Channel,,,y))
 $(eval $(call BuildPlugin,yjinglechan,,Jingle Channel,,,y))
```

**Comment by robho** [comment]
Thanks for taking a look Sebastian. I was planning to submit a patch for master also, but didn't know the order was important. I've created #648 which addresses your comments above and is for master.

I'll leave this PR open, if it's ok with you, and update it with a new diff once #648 has been closed.

**Comment by jslachta** [comment]
Hello Robert,

I acknowledge this PR.

Thank you!

Kind regards,
Jiri

**Pull request merged**
