### PR TITLE
Siproxd updates

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: @jslachta 
Compile tested: x86_64, arc, mips24kc
Run tested: mips24kc

Description:
Hi Jiri,

this is not related to FPIC. Just some stuff that caught my attention when checking siproxd.

Best regards,
Seb

### CODE REVIEW

**Comment by micmac1** [comment]
One observation from when I was run-testing that I'd like to comment on is that I actually had problems with that. I wanted to make the init script loads some modules but could not figure out how to do it. The config file that gets installed does not provide any configuration hints. In the end I used the config file from the source and started siproxd manually.

Maybe somebody who knows how to configure siproxd using uci commands could add comments to the config file to make it easier? Maybe @guidosarducci as he seems to know his way around? :)

Otherwise I'd be in favor of removing the uci config stuff and just installing a normal init script plus the default config file. Just my 2 cents.

Best regards,
Seb

**Comment by guidosarducci** [comment]
Hi Seb,
Seems like we had similar thoughts with these commits :-). I've had [a branch](https://github.com/guidosarducci/telephony/commits/siproxd-0.8.3dev) with some of your changes and several other commits tracking the latest siproxd 0.8.3 development version for a few months now. You're welcome to have a look through.

But I've held off doing another PR until @jslachta (hint hint) can backport my last [siproxd changes](https://github.com/openwrt/telephony/pull/164) from master to LEDE stable, given they are a big security and usability update. Would merging your changes delay a backport further? That would indeed be a shame.

On a related point, the siproxd 0.8.3 development [daily snapshots](http://siproxd.sourceforge.net/index.php?op=snapshot) disappear after a week, and the "bleedingedge" link to the latest snapshot would have a constantly changing package hash. As I'm not a deep Makefile expert, do you have any suggestion how best to track such a tarball via the Makefile PKG_SOURCE* variables?

>One observation from when I was run-testing that I'd like to comment on is that I actually had problems with that. I wanted to make the init script loads some modules but could not figure out how to do it. The config file that gets installed does not provide any configuration hints. In the end I used the config file from the source and started siproxd manually.

Hmm. Honestly, I didn't use that facility until recently trying to do more thorough testing for the 0.8.3 version, but it's straightforward: (e.g. to add call logging)
```
config siproxd 'general'
        option interface_inbound 'lan'
        option interface_outbound 'wan'
        list load_plugin 'plugin_logcall.so'
```
>Maybe somebody who knows how to configure siproxd using uci commands could add comments to the config file to make it easier? Maybe @guidosarducci as he seems to know his way around? :)

Good suggestion, I'll add it to my branch. I can see it's not completely obvious without reading the code that it's a 'list' option type, unless one guesses from the fact multiple plugins are supported.

Let me know if there are other `siproxd` configuration options you think people are likely to use, which also warrant some comments.

>Otherwise I'd be in favor of removing the uci config stuff and just installing a normal init script plus the default config file. Just my 2 cents.

Well, I can understand the frustration with `siproxd`, having gone through it myself before. But now having UCI and the ability to just specify 'lan' and 'wan' as defaults is a big usability win, letting the package work out-of-the-box and in a portable fashion.

>Best regards,
Seb

Kind regards and thanks for any help.

**Comment by micmac1** [comment]
Hi Guido,

Regarding the backports I'd suggest you just send a pull request to Jiri for the lede-17.01 branch.

Regarding the config file I think it should have enough comments so that users can make easy use of all features supported, like how to load certain modules and how to specify per-module config, how to configure generic items regarding logging etc. I appreciate that writing a commented config file is quite a lot of work. But without it people will just have problems using it, which would not be what we want :-)

Regards,
Seb

**Comment by guidosarducci** [comment]
Hi Seb,

>Regarding the backports I'd suggest you just send a pull request to Jiri for the lede-17.01 branch.

OK, will do that. Probably easiest anyway, yet the advice I had before was to make all PRs to master and then request backports to stable.

BTW, would you have any thoughts on my siproxd snapshot problem?
>On a related point, the siproxd 0.8.3 development daily snapshots disappear after a week, and the "bleedingedge" link to the latest snapshot would have a constantly changing package hash. As I'm not a deep Makefile expert, do you have any suggestion how best to track such a tarball via the Makefile PKG_SOURCE* variables?

Thanks again,
Tony

**Comment by micmac1** [comment]
Hi Tony,

I wouldn't track dev tarballs that keep  changing. That would be the opposite of a stable package. If there's a patch you think should be included then put it into the pull request. Just my 2 cents. :-)

Regards,
Seb

Am February 26, 2018 2:44:07 AM UTC schrieb guidosarducci <notifications@github.com>:

**Comment by guidosarducci** [comment]
Hi Seb,
>@micmac1 commented 6 days ago
>I wouldn't track dev tarballs that keep changing. That would be the opposite of a stable package. If there's a patch you think should be ### included then put it into the pull request. Just my 2 cents. :-)

Ideally, yes. But siproxd releases can be up to _5 years_ apart :-( so the infrequent dev updates serve as bugfix and point releases too. I'll try pinging the upstream author to follow up...

Behind my original question, I was wondering if there was some standard way to capture/host necessary tarballs on OpenWRT infrastructure?

>Regarding the backports I'd suggest you just send a pull request to Jiri for the lede-17.01 branch.

Yes, I don't want to hold up this PR's valid changes with @jslachta -- please go ahead and merge. I will PR later against `master` for additional improvements I've thought about since our discussion, and then make another PR for `lede-17.01` that consolidates all these changes for backport.

Kind regards,
Tony

**Comment by micmac1** [comment]
Hi Tony,

The snapshots have a date, though. So you could just pick one and put it into the Makefile. It will be put on the mirrors and if it vanishes from SF it'll be there on the OpenWrt mirrors still.

Have a good week!

Seb

**Comment by guidosarducci** [comment]
Excellent! That's great to know, and thanks for the tip. BTW, I included your changes in my upstream siproxd-0.8.3 branch and built/run to confirm that they work OK for LEDE 17.01.04 under ar71xx.

So this can get a "Tested-by:" from me if needed by @jslachta .

**Comment by jslachta** [comment]
Thank you for the good work. Should I merge the changes to for-17.01 branch?

**Comment by micmac1** [comment]
Hi Jiri,

I think Tony will send a separate pull request for 17.01 branch.

Thanks!
Seb

Am March 10, 2018 7:58:14 AM UTC schrieb Jiri Slachta <notifications@github.com>:

**Comment by guidosarducci** [comment]
Hi Jiri, Seb,

I will hold off doing a 17.01-branch PR for now. Once Seb's PR is merged I will:

1. Make another PR for `master`, including some improvements from discussions with Seb. These will be afad2a9, f3492b0, and 7021932.
2. After merging, create a PR for `lede-17.01`, bringing `siproxd` up to date with `master`. @jslachta This will be ~12 commits, so do you prefer I leave them separate or squash and summarize the commit messages?
3. After merging, I'll create a "WIP" PR for `master` to track upstream `siproxd` dev snapshots. Once there's a release or other motivating factor, I'll drop the "WIP" and ask to merge.

Does that work?

Thanks again!

**Comment by jslachta** [comment]
Hi Tony,

I am sorry for the delayed response. 

The most preferred way for stable branches is to cherry-pick these changes from master. You can also squash the changes if you wish. Your procedure with WIP PR is correct - however it must not be forgotten removing the floating target before the merge.

So yes, it can work that way.

Thank you.
Jiri

**Comment by guidosarducci** [comment]
Hi Jiri,

Thanks for the clarifications. I'll follow up first with the 3 commits for master, and then look at backporting considering your suggestions.

Take care,
Tony

**Pull request merged**
