### PR TITLE
[19.07] siproxd: update to version 0.8.3, improve logging and memory usage

### PR DESCRIPTION
**Pull request by guidosarducci**
**Maintainer**: @jslachta 
**Compile tested**: dir-835/mips_24kc/19.07.4 & ea6350v3/ipq40xx/19.07.4
**Run tested**: dir-835/mips_24kc/19.07.4 & ea6350v3/ipq40xx/19.07.4

**Description**:
This release includes bug fixes and improvements accumulated over the last
4 years of development snapshots [1].

Bump upstream version, build new plugins 'stats' and 'blacklist', and add
an 'sqlite3' package dependency for siproxd-mod-blacklist.

Disable procd capturing stderr to syslog, since siproxd in 'foreground'
mode writes both to syslog and stderr, duplicating log messages.

Include a patch to drastically reduce memory usage (RSS from 17MB to 5MB
on ipq40xx platform):

  * 005-reduce-rtpproxy-urlmap-size.patch

Drop the following patches now included upstream:

  * 010-syslog-msg.patch
  * 100-musl-compat.patch

[1] http://siproxd.sourceforge.net/index.php?op=changelog.

Signed-off-by: Tony Ambardar <itugrok@yahoo.com>

### CODE REVIEW

**Comment by guidosarducci** [comment]
@jslachta and @micmac1: Do you understand this build error with CircleCI? This is a straight backport of https://github.com/openwrt/telephony/pull/567, which I've build-tested using the SDK and run on 2 devices.

**Comment by micmac1** [comment]
Hi Tony, will check and get back to you tonight.

Am September 21, 2020 7:42:22 AM UTC schrieb guidosarducci <notifications@github.com>:
>@jslachta and @micmac1: Do you understand this build error with CircleCI? This is a straight backport of https://github.com/openwrt/telephony/pull/567, which I've build-tested using the SDK and run on 2 devices.
>

**Comment by micmac1** [comment]
Ah, no need to check anythinh. CircleCI isn't set up in openwrt-19.07 branch, so it will always fail. So no worries, it's expected to fail ;-)

**Comment by guidosarducci** [comment]
OK, thanks for confirming -- I was scratching my head for a while there!

**Review by jslachta — APPROVED** [review]

**Comment by jslachta** [comment]
Reviewed, compile and run tested. And works fine. Thank you!

**Pull request merged**
