### PR TITLE
Added FreeSWITCH stable package

### PR DESCRIPTION
**Pull request by micmac1**
Based on FS v1.6.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

Hi all!

I put this together based on the FreeSWITCH package that's already in the tree. I ripped some things out and added others (mainly ideas from OpenWRT's Asterisk packages as well as busybox buildroot's FreeSWITCH package).

The main idea was to get a stable version of FreeSwitch up and running. I put some effort into keeping the Makefile simple.

Regards,
Sebastian

### CODE REVIEW

**Comment by taeasy** [comment]
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking whether x86_64-openwrt-linux-musl-gcc needs -traditional... no
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... (cached) yes
checking return type of signal handlers... void
checking for strftime... (cached) yes
checking for gethostname... yes
checking for vasprintf... yes
checking for mmap... yes
checking for mlock... yes
checking for mlockall... yes
checking for usleep... yes
checking for getifaddrs... yes
checking for timerfd_create... yes
checking for getdtablesize... yes
checking for posix_openpt... yes
checking for poll... yes
checking for sched_setscheduler... yes
checking for setpriority... yes
checking for setrlimit... yes
checking for setgroups... yes
checking for initgroups... yes
checking for getrusage... yes
checking for wcsncmp... yes
checking for setgroups... (cached) yes
checking for asprintf... yes
checking for setenv... yes
checking for pselect... yes
checking for gettimeofday... (cached) yes
checking for localtime_r... yes
checking for gmtime_r... yes
checking for strcasecmp... yes
checking for stricmp... no
checking for _stricmp... no
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... no
checking for sched_setaffinity... yes
checking for sched_getaffinity... yes
checking whether the CPU_SET and CPU_ZERO macros are defined... yes
checking for clock_gettime in -lrt... yes
checking for clock_getres in -lrt... yes
checking for clock_nanosleep in -lrt... yes
checking for pthread_setschedparam in -lpthread... yes
checking for socket... yes
checking for /dev/ptmx... configure: error: cannot check for file existence when cross compiling
Makefile:318: recipe for target '/home/main/lede/build_dir/target-x86_64_musl-1.1.15/freeswitch-1.6.12/.configured_yyyyyyy' failed
make[2]: *** [/home/main/lede/build_dir/target-x86_64_musl-1.1.15/freeswitch-1.6.12/.configured_yyyyyyy] Error 1
make[2]: Leaving directory '/home/main/lede/feeds/telephony/net/freeswitch-stable'
package/Makefile:127: recipe for target 'package/feeds/telephony/freeswitch-stable/compile' failed
make[1]: *** [package/feeds/telephony/freeswitch-stable/compile] Error 2
make[1]: Leaving directory '/home/main/lede'
/home/main/lede/include/toplevel.mk:194: recipe for target 'package/freeswitch-stable/compile' failed
make: *** [package/freeswitch-stable/compile] Error 2
main@debian:~/lede$

**Comment by micmac1** [comment]
Thanks for info. I've made some changes and compile-tested on x86_64. Please let me know if it works out for you now.

**Comment by taeasy** [comment]
It's work now. thanks

**Comment by bobafetthotmail** [comment]
Wow, there is a ton of commits here. For a PR about adding a new package, you should squash them into a single one.

Github does not allow that, so you will need to use the command line to control git locally. 

**git reset HEAD~X** will delete X commits (if X was 10 then it would delete 10 commits, count the number of commits you made) but modified files will not be changed.

**git add -i** and then use its interface to add again the modified files to git

**git commit** to make a single commit for all this stuff

**git push -f** to send this to github and in this PR

Note that I don't have commit access here (I contributed to other package feeds), I just came looking after you posted in the lede-dev mailing list.

**Comment by micmac1** [comment]
Hi boba,

Yes, lots of commits. But the initial PR was just one commit :-) Anyway, I'll keep your tips in mind for later, thanks!

**Pull request closed without merging**
