### PR TITLE
rtpengine: fix compilation with GCC 10

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @micmac1 
Compile tested: ath79

### CODE REVIEW

**Comment by micmac1** [comment]
Hi @neheb,

I can't repro this. I also have

```
CONFIG_GCC_VERSION_10=y
CONFIG_GCC_VERSION="10.1.0"
```

and use

`make -j2 package/libsrtp2/{clean,compile} V=s`

but rtpengine compiles fine. Do you use some special setting to make it fail?

**Comment by neheb** [comment]
Strange.

**Comment by neheb** [comment]
Wait what does libsrtp2 have to do with rtpengine?

**Comment by neheb** [comment]
https://github.com/openwrt/telephony/pull/554 fixes this too. Closing.

**Pull request closed without merging**
