### PR TITLE
freeswitch: fix compilation with musl 1.2.0

### PR DESCRIPTION
**Pull request by neheb**
Fix patch 230 as it's a patch of a patch with fuzz and wrong offsets.

Refresh other patches.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @micmac1 
Compile tested: powerpc

### CODE REVIEW

**Comment by neheb** [comment]
Fixes: https://github.com/openwrt/telephony/issues/600

**Comment by micmac1** [comment]
Hi there,

This commit removes the AC_TRY_RUN->AC_COMPILE_IFELSE replacement. And the subject line is wrong. Do you want to take another crack at this or do you want me to do it? Apart from that it would be nice to know how it actually fails for you (reproducer).

Kind regards,
Seb

**Comment by micmac1** [comment]
Happy New Year by the way!

**Comment by neheb** [comment]
> Hi there,
> 
> This commit removes the AC_TRY_RUN->AC_COMPILE_IFELSE replacement.

Upstream actually changed the makefile. It additionally checks whether or not it's being cross compiled making it no/op. Which is why I removed the section.

> And the subject line is wrong.

Meh I thought the issue was with musl 1.2.x. I don't actually know what the core issue is. My guess is some old version of some tool that comes with CentOS 7.

> Do you want to take another crack at this or do you want me to do it?

I'll edit the commit subject.

> Apart from that it would be nice to know how it actually fails for you (reproducer).
> 
> Kind regards,
> Seb

I think it's actually some issue with CentOS 7's quilt or something. It doesn't like fuzz.

**Comment by micmac1** [comment]
Makes sense. Thanks!

**Pull request merged**
