### PR TITLE
freeswitch-stable: add mod_signalwire and dependencies

### PR DESCRIPTION
**Pull request by micmac1**
Maintainer: me
Compile tested: master ath79
Run tested: N/A

Description:
Hi all,

**Please don't merge (yet)**. This is what I came up with regarding issue #413.

@skyblaster, do you want to run-test this and let us know afterwards your opinion regarding if and why this should be part of the telephony repo?

Regards,
Seb

### CODE REVIEW

**Comment by skyblaster** [comment]
Hi @micmac1 
Sorry for the delay. I'm finally getting around to testing this.
First, I performed a fresh git checkout of master, switched to the v19.07.0-rc2 branch, downloaded your new files and then built the new packages. Everything compiled without error.
I then installed these new packages alongside the pre-built 19.07.0-rc2 image and freeswitch-stable packages. Again, no errors or warnings.

When I try to make an "integration" with Signalwire, I'm presented with the following errors (values obscured to protect the innocent):
`2019-12-11 19:04:14.905260 [INFO] mod_signalwire.c:404 SignalWire adoption of this FreeSWITCH completed
2019-12-11 19:04:16.345263 [INFO] mod_signalwire.c:524 SignalWire Session State Change: [Normal=>Online] Status: 0 Reason: Manager completed state change request
2019-12-11 19:04:20.305261 [INFO] mod_signalwire.c:1030 Connected to SignalWire
2019-12-11 19:04:21.565258 [DEBUG] mod_signalwire.c:1103 "<?xml version="1.0"?><document type="freeswitch/xml"><section name="configuration" description="Various Configuration"><configuration name="sofia.conf" description="sofia Endpoint"><profiles><profile name="signalwire"><gateways><gateway name="signalwire"><param name="username" value="1312c096c59560ebb133ee73a77ef52c" /><param name="password" value="b34f516fc355faab67efe43cf5d3cbb9" /><param name="proxy" value="test-a1370aa89c7122679b9f230135c17f4e.sip.signalwire.com" /><param name="register" value="true" /><param name="register-transport" value="tls" /><param name="extension" value="auto_to_user" /><param name="dtmf-type" value="rfc2833" /><param name="caller-id-in-from" value="false" /><variables><variable name="rtp_secure_media" value="optional:AEAD_AES_256_GCM_8:AES_256_CM_HMAC_SHA1_80:AES_CM_128_HMAC_SHA1_80:AES_256_CM_HMAC_SHA1_32:AES_CM_128_HMAC_SHA1_32" /></variables></gateway></gateways><settings><param name="debug" value="0" /><param name="dialplan" value="signalwire" /><param name="context" value="default" /><param name="rtp-timer-name" value="soft" /><param name="rtp-ip" value="192.168.1.100" /><param name="sip-ip" value="192.168.1.100" /><param name="ext-rtp-ip" value="69.191.46.77" /><param name="ext-sip-ip" value="69.191.46.77" /><param name="rtp-timeout-sec" value="300" /><param name="rtp-hold-timeout-sec" value="1800" /><param name="sip-port" value="6050" /><param name="tls" value="True" /><param name="tls-only" value="true" /><param name="tls-bind-params" value="transport=tls" /><param name="tls-sip-port" value="6050" /><param name="tls-verify-date" value="true" /><param name="tls-verify-policy" value="none" /><param name="tls-verify-depth" value="2" /><param name="codec-prefs" value="OPUS,G722,PCMU,PCMA,G729,VP8,H264" /><param name="inbound-codec-negotiation" value="generous" /><param name="inbound-late-negotiation" value="true" /><param name="manage-presence" value="false" /><param name="auth-calls" value="false" /></settings></profile></profiles></configuration></section></document>"
2019-12-11 19:04:21.565258 [INFO] mod_signalwire.c:1142 gwlist = "Invalid Profile [signalwire]"
2019-12-11 19:04:21.565258 [INFO] mod_signalwire.c:1115 profile MD5 = "96cdea045520f9d502cf4ac991dbaba2"
2019-12-11 19:04:21.565258 [INFO] mod_signalwire.c:1129 Received configuration from SignalWire
2019-12-11 19:04:22.565262 [DEBUG] mod_signalwire.c:1220 Starting SignalWire SIP profile
2019-12-11 19:04:22.585273 [INFO] switch_xml.c:1372 No files to include at /etc/freeswitch/autoload_configs/../sip_profiles/external-ipv6/*.xml
2019-12-11 19:04:22.605258 [INFO] switch_xml.c:1372 No files to include at /etc/freeswitch/autoload_configs/../sip_profiles/internal/*.xml
2019-12-11 19:04:22.805261 [DEBUG] mod_signalwire.c:558 Received XML lookup for SignalWire SIP profile
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 debug [0]
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 dialplan [signalwire]
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 context [default]
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 rtp-timer-name [soft]
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 rtp-ip [192.168.1.100]
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 sip-ip [192.168.1.100]
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 ext-rtp-ip [69.191.46.77]
2019-12-11 19:04:22.805261 [INFO] switch_time.c:1433 Timezone reloaded 530 definitions
2019-12-11 19:04:22.805261 [DEBUG] sofia.c:4597 ext-sip-ip [69.191.46.77]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 rtp-timeout-sec [300]
2019-12-11 19:04:22.828160 [WARNING] sofia.c:5192 rtp-timeout-sec deprecated use media_timeout variable.
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 rtp-hold-timeout-sec [1800]
2019-12-11 19:04:22.828160 [WARNING] sofia.c:5199 rtp-hold-timeout-sec deprecated use media_hold_timeout variable.
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 sip-port [6050]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 tls [True]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 tls-only [true]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 tls-bind-params [transport=tls]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 tls-sip-port [6050]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 tls-verify-date [true]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 tls-verify-policy [none]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 tls-verify-depth [2]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 codec-prefs [OPUS,G722,PCMU,PCMA,G729,VP8,H264]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 inbound-codec-negotiation [generous]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 inbound-late-negotiation [true]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 manage-presence [false]
2019-12-11 19:04:22.828160 [DEBUG] sofia.c:4597 auth-calls [false]
2019-12-11 19:04:22.828160 [NOTICE] sofia.c:5982 NAT detected setting external ip to 69.191.46.77
2019-12-11 19:04:22.828160 [INFO] sofia.c:5988 Setting nonce TTL to 60 seconds
2019-12-11 19:04:22.828160 [INFO] sofia.c:5993 Setting MAX Auth Validity to 0 Attempts
2019-12-11 19:04:35.585250 [DEBUG] sofia_reg.c:2457 Changing expire time to 108 by request of proxy sip:callcentric.com
2019-12-11 19:04:44.905248 [NOTICE] sofia.c:6160 Started Profile signalwire [sofia_reg_signalwire]
2019-12-11 19:04:44.905248 [DEBUG] sofia.c:3134 Creating agent for signalwire
2019-12-11 19:04:44.925259 [DEBUG] sofia.c:3150 Created TCP nat mapping for signalwire port 6050
2019-12-11 19:04:44.945287 [DEBUG] sofia.c:3154 Created TCP/TLS nat mapping for signalwire port 6050
2019-12-11 19:04:44.945287 [ERR] sofia.c:3235 Error Creating SIP UA for profile: signalwire (sip:mod_sofia@192.168.1.100:6050;transport=udp,tcp) ATTEMPT 1 (RETRY IN 5 SEC)
2019-12-11 19:04:45.905257 [INFO] mod_signalwire.c:1142 gwlist = "Invalid Profile [signalwire]"
2019-12-11 19:04:45.905257 [WARNING] mod_signalwire.c:1248 Failed to start SignalWire SIP gateway`

**Comment by skyblaster** [comment]
I compiled again for target x86 and tested in VirtualBox. Getting the same results using the vanilla configs.

I compared against a standard Debian netinstall and the signalwire connector worked without issue.

**Comment by micmac1** [comment]
On Sat, Dec 14, 2019 at 02:01:59PM -0800, skyblaster wrote:
> I compiled again for target x86 and tested in VirtualBox. Getting the same results using the vanilla configs.
>
> I compared against a standard Debian netinstall and the signalwire connector worked without issue.

No clue. Thanks for testing. If it doesn't work it doesn't work.

**Comment by skyblaster** [comment]
Did a little digging as I was also seeing the same error on the Internal profile for one of my vanilla instances.
When I change the following in vars.xml to true under my Internal profile, it also fails to start.
`<X-PRE-PROCESS cmd="set" data="internal_ssl_enable=false"/>`

`Error Creating SIP UA for profile: internal`

Previous tickets regarding this issue claim the following fix the problem:
> Install openssl and openss-devel. Recompile Freeswitch!

Since I don't have any TLS trunks/SIP profiles and SignalWire depends heavily on encryption, I bet I will need to recompile with extra flags enabled somewhere.

**Comment by micmac1** [comment]
> Did a little digging as I was also seeing the same error on the Internal profile for one of my vanilla instances.
> When I change the following in vars.xml to true under my Internal profile, it also fails to start.
> `<X-PRE-PROCESS cmd="set" data="internal_ssl_enable=false"/>`
>
> `Error Creating SIP UA for profile: internal`
>
> Previous tickets regarding this issue claim the following fix the problem:
> > Install openssl and openss-devel. Recompile Freeswitch!
>
> Since I don't have any TLS trunks/SIP profiles and SignalWire depends heavily on encryption, I bet I will need to recompile with extra flags enabled somewhere.

The packages for signalwire-c and libks already depend on OpenSSL, so
does freeswitch. I think that should be fine already. I'm pretty sure
that the software would actually complain if OpenSSL wasn't available
during compilation.

**Comment by skyblaster** [comment]
In my case however, it doesn't appear FreeSWITCH and/or mod_sofia was built with OpenSSL features/flags.
When I simply enable SSL for the external profile in vars.xml and then "reloadxml" and "reload mod_sofia", my external profiles fail to start in the exact same way.

`<X-PRE-PROCESS cmd="set" data="external_ssl_enable=true"/>`

**Comment by micmac1** [comment]
> In my case however, it doesn't appear FreeSWITCH and/or mod_sofia was
> built with OpenSSL features/flags.  When I simply enable SSL for the
> external profile in vars.xml and then "reloadxml" and "reload
> mod_sofia", my external profiles fail to start in the exact same way.
>
> `<X-PRE-PROCESS cmd="set" data="external_ssl_enable=true"/>`

root@archer:~# ldd /usr/bin/freeswitch |egrep "ssl|crypt"
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x7765e000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x774f6000)
	libmbedcrypto.so.1 => /usr/lib/libmbedcrypto.so.1 (0x77402000)
root@archer:~#

Check if your freeswitch was compiled against OpenSSL like above.

I was testing TLS a few weeks back for a pull request and it worked fine.

**Comment by skyblaster** [comment]
On my RPi2 running OpenWrt:
```
root@pi:~# ldd /usr/bin/freeswitch |egrep "ssl|crypt"
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x76aee000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x76929000)
	libmbedcrypto.so.3 => /usr/lib/libmbedcrypto.so.3 (0x76854000)
```

On my Debian 10 instance running the pre-built FreeSWITCH packages:
```
root@debian:/etc/freeswitch/dialplan/public# ldd /usr/bin/freeswitch |egrep "ssl|crypt"
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f2996833000)
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f29967a1000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f29964b8000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f299517a000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f2994b81000)
```

**Comment by micmac1** [comment]
> On my RPi2 running OpenWrt:
> ```
> root@pi:~# ldd /usr/bin/freeswitch |egrep "ssl|crypt"
> 	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x76aee000)
> 	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x76929000)
> 	libmbedcrypto.so.3 => /usr/lib/libmbedcrypto.so.3 (0x76854000)
> ```

Looks ok to me.

**Comment by skyblaster** [comment]
I should probably open a new ticket since this is going off topic from mod_signalwire, however under OpenWrt, I'm never able to see (TLS) profiles such as this:
```
freeswitch@debian> sofia status
                     Name	   Type	                                      Data	State
=================================================================================================
                 external	profile	           sip:mod_sofia@69.191.46.77:5081	RUNNING (0) (TLS)

```

If I change the following to true in vars.xml and restart FreeSWITCH, all external profiles fail to start:
`<X-PRE-PROCESS cmd="set" data="external_ssl_enable=false"/>`

I just tested this on target x86_64 for 18.06.5, 19.07.0-rc2, as well as the latest snapshot all from https://downloads.openwrt.org/ followed by:
```
# opkg update
# opkg install freeswitch-stable freeswitch-stable-example-minimal freeswitch-stable-example-vanilla freeswitch-stable-mod-blacklist freeswitch-stable-mod-commands freeswitch-stable-mod-dialplan-xml freeswitch-stable-mod-dptools freeswitch-stable-mod-event-socket freeswitch-stable-mod-hash freeswitch-stable-mod-loopback freeswitch-stable-mod-native-file freeswitch-stable-mod-say-en freeswitch-stable-mod-sndfile freeswitch-stable-mod-sofia freeswitch-stable-mod-voicemail freeswitch-stable-util-fs-cli freeswitch-stable-util-gentls-cert
# cd /etc/freeswitch
# cp /usr/share/freeswitch/examples/vanilla/* . -r
# cp /usr/share/freeswitch/examples/vanilla/*.* . -r
# vi /etc/config/freeswitch  <-- toggle enable from 0 to 1
# /etc/init.d/freeswitch start
# fs_cli
```

Am I missing anything?

**Comment by skyblaster** [comment]
I found the issue! File permissions. After running the following. My TLS issues are solved.
Now back to testing mod_signalwire ;-)

```
# cd /etc/freeswitch
# chown freeswitch:freeswitch . -R
```

**Comment by skyblaster** [comment]
I believe mod_signalwire can be deemed working, however I'm not having much luck with matching the incoming regex.

Thanks for all of your help @micmac1 !

**Comment by skyblaster** [comment]
Using the dialplan found in the following tutorial, I'm happy to report that mod_signalwire works.
https://docs.google.com/presentation/d/1nd8nMh_sMVJb-WsxDdS69LPBfmd6CgABg7j-RDp08B4/edit#slide=id.g4b5463e36c_0_5

As to why should this be part of the telephony repo? You've already done the heavy lifting, so I don't see the harm. It could be of great value to users who want inexpensive DIDs and don't make many calls in a month. I'm hopeful that upstream changes will be infrequent and the packages are easy to maintain.

**Comment by micmac1** [comment]
> Using the dialplan found in the following tutorial, I'm happy to
> report that mod_signalwire works.
> https://docs.google.com/presentation/d/1nd8nMh_sMVJb-WsxDdS69LPBfmd6CgABg7j-RDp08B4/edit#slide=id.g4b5463e36c_0_5

Thanks again for testing.

> As to why should this be part of the telephony repo? You've already
> done the heavy lifting, so I don't see the harm. It could be of great
> value to users who want inexpensive DIDs and don't make many calls in
> a month. I'm hopeful that upstream changes will be infrequent and the
> packages are easy to maintain.

Thanks for the feedback as well. I'll add the commits to master and
19.07. I should be able to do so in a day or two.

Kind regards,
Seb

**Pull request merged**
